#!/usr/bin/env python3
# All right reserved 2013
# Description: Dota 2 Library (Heroes)
# URL: http://github.com/Lardjo

heroes = {

    1: {'name': 'Anti-Mage', 'avatar': 'img/dota/heroes/antimage.png'},
    2: {'name': 'Axe', 'avatar': 'img/dota/heroes/axe.png'},
    3: {'name': 'Ban', 'avatar': 'img/dota/heroes/bane.png'},
    4: {'name': 'Bloodseeker', 'avatar': 'img/dota/heroes/bloodseeker.png'},
    5: {'name': 'Crystal Maiden', 'avatar': 'img/dota/heroes/crystal_maiden.png'},
    6: {'name': 'Drow Ranger', 'avatar': 'img/dota/heroes/drow_ranger.png'},
    7: {'name': 'Earthshaker', 'avatar': 'img/dota/heroes/earthshaker.png'},
    8: {'name': 'Juggernaut', 'avatar': 'img/dota/heroes/juggernaut.png'},
    9: {'name': 'Mirana', 'avatar': 'img/dota/heroes/mirana.png'},
    10: {'name': 'Morphling', 'avatar': 'img/dota/heroes/morphling.png'},
    11: {'name': 'Shadow Fiend', 'avatar': 'img/dota/heroes/nevermore.png'},
    12: {'name': 'Phantom Lancer', 'avatar': 'img/dota/heroes/phantom_lancer.png'},
    13: {'name': 'Puck', 'avatar': 'img/dota/heroes/puck.png'},
    14: {'name': 'Pudge', 'avatar': 'img/dota/heroes/pudge.png'},
    15: {'name': 'Razor', 'avatar': 'img/dota/heroes/razor.png'},
    16: {'name': 'Sand King', 'avatar': 'img/dota/heroes/sand_king.png'},
    17: {'name': 'Storm Spirit', 'avatar': 'img/dota/heroes/storm_spirit.png'},
    18: {'name': 'Sven', 'avatar': 'img/dota/heroes/sven.png'},
    19: {'name': 'Tiny', 'avatar': 'img/dota/heroes/tiny.png'},
    20: {'name': 'Vengeful Spirit', 'avatar': 'img/dota/heroes/vengefulspirit.png'},
    21: {'name': 'Windranger', 'avatar': 'img/dota/heroes/windrunner.png'},
    22: {'name': 'Zeus', 'avatar': 'img/dota/heroes/zuus.png'},
    23: {'name': 'Kunkka', 'avatar': 'img/dota/heroes/kunkka.png'},
    25: {'name': 'Lina', 'avatar': 'img/dota/heroes/lina.png'},
    26: {'name': 'Lion', 'avatar': 'img/dota/heroes/lion.png'},
    27: {'name': 'Shadow Shaman', 'avatar': 'img/dota/heroes/shadow_shaman.png'},
    28: {'name': 'Slardar', 'avatar': 'img/dota/heroes/slardar.png'},
    29: {'name': 'Tidehunter', 'avatar': 'img/dota/heroes/tidehunter.png'},
    30: {'name': 'Witch Doctor', 'avatar': 'img/dota/heroes/witch_doctor.png'},
    31: {'name': 'Lich', 'avatar': 'img/dota/heroes/lich.png'},
    32: {'name': 'Riki', 'avatar': 'img/dota/heroes/riki.png'},
    33: {'name': 'Enigma', 'avatar': 'img/dota/heroes/enigma.png'},
    34: {'name': 'Tinker', 'avatar': 'img/dota/heroes/tinker.png'},
    35: {'name': 'Sniper', 'avatar': 'img/dota/heroes/sniper.png'},
    36: {'name': 'Necrophos', 'avatar': 'img/dota/heroes/necrolyte.png'},
    37: {'name': 'Warlock', 'avatar': 'img/dota/heroes/warlock.png'},
    38: {'name': 'Beastmaster', 'avatar': 'img/dota/heroes/beastmaster.png'},
    39: {'name': 'Queen of Pain', 'avatar': 'img/dota/heroes/queenofpain.png'},
    40: {'name': 'Venomancer', 'avatar': 'img/dota/heroes/venomancer.png'},
    41: {'name': 'Faceless Void', 'avatar': 'img/dota/heroes/faceless_void.png'},
    42: {'name': 'Skeleton King', 'avatar': 'img/dota/heroes/skeleton_king.png'},
    43: {'name': 'Death Prophet', 'avatar': 'img/dota/heroes/death_prophet.png'},
    44: {'name': 'Phantom Assassin', 'avatar': 'img/dota/heroes/phantom_assassin.png'},
    45: {'name': 'Pugna', 'avatar': 'img/dota/heroes/pugna.png'},
    46: {'name': 'Templar Assassin', 'avatar': 'img/dota/heroes/templar_assassin.png'},
    47: {'name': 'Viper', 'avatar': 'img/dota/heroes/viper.png'},
    48: {'name': 'Luna', 'avatar': 'img/dota/heroes/luna.png'},
    49: {'name': 'Dragon Knight', 'avatar': 'img/dota/heroes/dragon_knight.png'},
    50: {'name': 'Dazzle', 'avatar': 'img/dota/heroes/dazzle.png'},
    51: {'name': 'Clockwerk', 'avatar': 'img/dota/heroes/rattletrap.png'},
    52: {'name': 'Leshrac', 'avatar': 'img/dota/heroes/leshrac.png'},
    53: {'name': 'Nature\'s Prophet', 'avatar': 'img/dota/heroes/furion.png'},
    54: {'name': 'Lifestealer', 'avatar': 'img/dota/heroes/life_stealer.png'},
    55: {'name': 'Dark Seer', 'avatar': 'img/dota/heroes/dark_seer.png'},
    56: {'name': 'Clinkz', 'avatar': 'img/dota/heroes/clinkz.png'},
    57: {'name': 'Omniknight', 'avatar': 'img/dota/heroes/omniknight.png'},
    58: {'name': 'Enchantress', 'avatar': 'img/dota/heroes/enchantress.png'},
    59: {'name': 'Huskar', 'avatar': 'img/dota/heroes/huskar.png'},
    60: {'name': 'Night Stalker', 'avatar': 'img/dota/heroes/night_stalker.png'},
    61: {'name': 'Broodmother', 'avatar': 'img/dota/heroes/broodmother.png'},
    62: {'name': 'Bounty Hunter', 'avatar': 'img/dota/heroes/bounty_hunter.png'},
    63: {'name': 'Weaver', 'avatar': 'img/dota/heroes/weaver.png'},
    64: {'name': 'Jakiro', 'avatar': 'img/dota/heroes/jakiro.png'},
    65: {'name': 'Batrider', 'avatar': 'img/dota/heroes/batrider.png'},
    66: {'name': 'Chen', 'avatar': 'img/dota/heroes/chen.png'},
    67: {'name': 'Spectre', 'avatar': 'img/dota/heroes/spectre.png'},
    68: {'name': 'Ancient Apparition', 'avatar': 'img/dota/heroes/ancient_apparition.png'},
    69: {'name': 'Doom Bringer', 'avatar': 'img/dota/heroes/doom_bringer.png'},
    70: {'name': 'Ursa', 'avatar': 'img/dota/heroes/ursa.png'},
    71: {'name': 'Spirit Breaker', 'avatar': 'img/dota/heroes/spirit_breaker.png'},
    72: {'name': 'Gyrocopter', 'avatar': 'img/dota/heroes/gyrocopter.png'},
    73: {'name': 'Alchemist', 'avatar': 'img/dota/heroes/alchemist.png'},
    74: {'name': 'Invoker', 'avatar': 'img/dota/heroes/invoker.png'},
    75: {'name': 'Silencer', 'avatar': 'img/dota/heroes/silencer.png'},
    76: {'name': 'Outworld Devourer', 'avatar': 'img/dota/heroes/obsidian_destroyer.png'},
    77: {'name': 'Lycan', 'avatar': 'img/dota/heroes/lycan.png'},
    78: {'name': 'Brewmaster', 'avatar': 'img/dota/heroes/brewmaster.png'},
    79: {'name': 'Shadow Demon', 'avatar': 'img/dota/heroes/shadow_demon.png'},
    80: {'name': 'Lone Druid', 'avatar': 'img/dota/heroes/lone_druid.png'},
    81: {'name': 'Chaos Knight', 'avatar': 'img/dota/heroes/chaos_knight.png'},
    82: {'name': 'Meepo', 'avatar': 'img/dota/heroes/meepo.png'},
    83: {'name': 'Treant Protector', 'avatar': 'img/dota/heroes/treant.png'},
    84: {'name': 'Ogre Magi', 'avatar': 'img/dota/heroes/ogre_magi.png'},
    85: {'name': 'Undying', 'avatar': 'img/dota/heroes/undying.png'},
    86: {'name': 'Rubick', 'avatar': 'img/dota/heroes/rubick.png'},
    87: {'name': 'Disruptor', 'avatar': 'img/dota/heroes/disruptor.png'},
    88: {'name': 'Nyx Assassin', 'avatar': 'img/dota/heroes/nyx_assassin.png'},
    89: {'name': 'Naga Siren', 'avatar': 'img/dota/heroes/naga_siren.png'},
    90: {'name': 'Keeper of the Light', 'avatar': 'img/dota/heroes/keeper_of_the_light.png'},
    91: {'name': 'Io', 'avatar': 'img/dota/heroes/wisp.png'},
    92: {'name': 'Visage', 'avatar': 'img/dota/heroes/visage.png'},
    93: {'name': 'Slark', 'avatar': 'img/dota/heroes/slark.png'},
    94: {'name': 'Medusa', 'avatar': 'img/dota/heroes/medusa.png'},
    95: {'name': 'Troll Warlord', 'avatar': 'img/dota/heroes/troll_warlord.png'},
    96: {'name': 'Centaur Warrunner', 'avatar': 'img/dota/heroes/centaur.png'},
    97: {'name': 'Magnus', 'avatar': 'img/dota/heroes/magnataur.png'},
    98: {'name': 'Timbersaw', 'avatar': 'img/dota/heroes/shredder.png'},
    99: {'name': 'Bristleback', 'avatar': 'img/dota/heroes/bristleback.png'},
    100: {'name': 'Tusk', 'avatar': 'img/dota/heroes/tusk.png'},
    101: {'name': 'Skywrath Mage', 'avatar': 'img/dota/heroes/skywrath_mage.png'},
    102: {'name': 'Abaddon', 'avatar': 'img/dota/heroes/abaddon.png'},
    103: {'name': 'Elder Titan', 'avatar': 'img/dota/heroes/elder_titan.png'},
    104: {'name': 'Legion Commander', 'avatar': 'img/dota/heroes/legion_commander.png'},
    106: {'name': 'Ember Spirit', 'avatar': 'img/dota/heroes/ember_spirit.png'},
    107: {'name': 'Earth Spirit', 'avatar': 'img/dota/heroes/earth_spirit.png'}
    #108 Abyssal Underlord Unreleased
    #109 Terrorblade Unreleased
}