#!/usr/bin/env python3
# All right reserved 2013
# Description: Dota 2 Library (Heroes)
# URL: http://github.com/Lardjo

heroes = {

    1: {'name': 'Anti-Mage',
        'avatar': 'img/dota/heroes/antimage.png',
        'ability': [{'id': 5003, 'image': 'img/dota/spellicons/antimage_mana_break.png'},
                    {'id': 5004, 'image': 'img/dota/spellicons/antimage_blink.png'},
                    {'id': 5005, 'image': 'img/dota/spellicons/antimage_spell_shield.png'},
                    {'id': 5006, 'image': 'img/dota/spellicons/antimage_mana_void.png'}]},
    2: {'name': 'Axe',
        'avatar': 'img/dota/heroes/axe.png',
        'ability': [{'id': 5007, 'image': 'img/dota/spellicons/axe_berserkers_call.png'},
                    {'id': 5008, 'image': 'img/dota/spellicons/axe_battle_hunger.png'},
                    {'id': 5009, 'image': 'img/dota/spellicons/axe_counter_helix.png'},
                    {'id': 5010, 'image': 'img/dota/spellicons/axe_culling_blade.png'}]},
    3: {'name': 'Bane',
        'avatar': 'img/dota/heroes/bane.png',
        'ability': [{'id': 5012, 'image': 'img/dota/spellicons/bane_enfeeble.png'},
                    {'id': 5011, 'image': 'img/dota/spellicons/bane_brain_sap.png'},
                    {'id': 5014, 'image': 'img/dota/spellicons/bane_nightmare.png'},
                    {'id': 5013, 'image': 'img/dota/spellicons/bane_fiends_grip.png'}]},
    4: {'name': 'Bloodseeker',
        'avatar': 'img/dota/heroes/bloodseeker.png',
        'ability': [{'id': 5015, 'image': 'img/dota/spellicons/bloodseeker_bloodrage.png'},
                    {'id': 5016, 'image': 'img/dota/spellicons/bloodseeker_blood_bath.png'},
                    {'id': 5017, 'image': 'img/dota/spellicons/bloodseeker_thirst.png'},
                    {'id': 5018, 'image': 'img/dota/spellicons/bloodseeker_rupture.png'}]},
    5: {'name': 'Crystal Maiden',
        'avatar': 'img/dota/heroes/crystal_maiden.png',
        'ability': [{'id': 5126, 'image': 'img/dota/spellicons/crystal_maiden_crystal_nova.png'},
                    {'id': 5127, 'image': 'img/dota/spellicons/crystal_maiden_frostbite.png'},
                    {'id': 5128, 'image': 'img/dota/spellicons/crystal_maiden_brilliance_aura.png'},
                    {'id': 5129, 'image': 'img/dota/spellicons/crystal_maiden_freezing_field.png'}]},
    6: {'name': 'Drow Ranger',
        'avatar': 'img/dota/heroes/drow_ranger.png',
        'ability': [{'id': 5019, 'image': 'img/dota/spellicons/drow_ranger_frost_arrows.png'},
                    {'id': 5632, 'image': 'img/dota/spellicons/drow_ranger_silence.png'},
                    {'id': 5021, 'image': 'img/dota/spellicons/drow_ranger_trueshot.png'},
                    {'id': 5022, 'image': 'img/dota/spellicons/drow_ranger_marksmanship.png'}]},
    7: {'name': 'Earthshaker',
        'avatar': 'img/dota/heroes/earthshaker.png',
        'ability': [{'id': 5023, 'image': 'img/dota/spellicons/earthshaker_fissure.png'},
                    {'id': 5024, 'image': 'img/dota/spellicons/earthshaker_enchant_totem.png'},
                    {'id': 5025, 'image': 'img/dota/spellicons/earthshaker_aftershock.png'},
                    {'id': 5026, 'image': 'img/dota/spellicons/earthshaker_echo_slam.png'}]},
    8: {'name': 'Juggernaut',
        'avatar': 'img/dota/heroes/juggernaut.png',
        'ability': [{'id': 5028, 'image': 'img/dota/spellicons/juggernaut_blade_fury.png'},
                    {'id': 5029, 'image': 'img/dota/spellicons/juggernaut_healing_ward.png'},
                    {'id': 5027, 'image': 'img/dota/spellicons/juggernaut_blade_dance.png'},
                    {'id': 5030, 'image': 'img/dota/spellicons/juggernaut_omni_slash.png'}]},
    9: {'name': 'Mirana',
        'avatar': 'img/dota/heroes/mirana.png',
        'ability': [{'id': 5051, 'image': 'img/dota/spellicons/mirana_starfall.png'},
                    {'id': 5048, 'image': 'img/dota/spellicons/mirana_arrow.png'},
                    {'id': 5050, 'image': 'img/dota/spellicons/mirana_leap.png'},
                    {'id': 5049, 'image': 'img/dota/spellicons/mirana_invis.png'}]},
    10: {'name': 'Morphling', 'avatar': 'img/dota/heroes/morphling.png'},
    11: {'name': 'Shadow Fiend', 'avatar': 'img/dota/heroes/nevermore.png'},
    12: {'name': 'Phantom Lancer', 'avatar': 'img/dota/heroes/phantom_lancer.png'},
    13: {'name': 'Puck', 'avatar': 'img/dota/heroes/puck.png'},
    14: {'name': 'Pudge',
         'avatar': 'img/dota/heroes/pudge.png',
         'ability': [{'id': 5075, 'image': 'img/dota/spellicons/pudge_meat_hook.png'},
                     {'id': 5076, 'image': 'img/dota/spellicons/pudge_rot.png'},
                     {'id': 5074, 'image': 'img/dota/spellicons/pudge_flesh_heap.png'},
                     {'id': 5077, 'image': 'img/dota/spellicons/pudge_dismember.png'}]},
    15: {'name': 'Razor', 'avatar': 'img/dota/heroes/razor.png'},
    16: {'name': 'Sand King',
         'avatar': 'img/dota/heroes/sand_king.png',
         'ability': [{'id': 5102, 'image': 'img/dota/spellicons/sandking_burrowstrike.png'},
                     {'id': 5103, 'image': 'img/dota/spellicons/sandking_sand_storm.png'},
                     {'id': 5104, 'image': 'img/dota/spellicons/sandking_caustic_finale.png'},
                     {'id': 5105, 'image': 'img/dota/spellicons/sandking_epicenter.png'}]},
    17: {'name': 'Storm Spirit',
         'avatar': 'img/dota/heroes/storm_spirit.png',
         'ability': [{'id': 5098, 'image': 'img/dota/spellicons/storm_spirit_static_remnant.png'},
                     {'id': 5099, 'image': 'img/dota/spellicons/storm_spirit_electric_vortex.png'},
                     {'id': 5100, 'image': 'img/dota/spellicons/storm_spirit_overload.png'},
                     {'id': 5101, 'image': 'img/dota/spellicons/storm_spirit_ball_lightning.png'}]},
    18: {'name': 'Sven',
         'avatar': 'img/dota/heroes/sven.png',
         'ability': [{'id': 5094, 'image': 'img/dota/spellicons/sven_storm_bolt.png'},
                     {'id': 5095, 'image': 'img/dota/spellicons/sven_great_cleave.png'},
                     {'id': 5096, 'image': 'img/dota/spellicons/sven_warcry.png'},
                     {'id': 5097, 'image': 'img/dota/spellicons/sven_gods_strength.png'}]},
    19: {'name': 'Tiny',
         'avatar': 'img/dota/heroes/tiny.png',
         'ability': [{'id': 5106, 'image': 'img/dota/spellicons/tiny_avalanche.png'},
                     {'id': 5107, 'image': 'img/dota/spellicons/tiny_toss.png'},
                     {'id': 5108, 'image': 'img/dota/spellicons/tiny_craggy_exterior.png'},
                     {'id': 5109, 'image': 'img/dota/spellicons/tiny_grow.png'}]},
    20: {'name': 'Vengeful Spirit', 'avatar': 'img/dota/heroes/vengefulspirit.png'},
    21: {'name': 'Windranger',
         'avatar': 'img/dota/heroes/windrunner.png',
         'ability': [{'id': 5130, 'image': 'img/dota/spellicons/windrunner_shackleshot.png'},
                     {'id': 5131, 'image': 'img/dota/spellicons/windrunner_powershot.png'},
                     {'id': 5132, 'image': 'img/dota/spellicons/windrunner_windrun.png'},
                     {'id': 5133, 'image': 'img/dota/spellicons/windrunner_focusfire.png'}]},
    22: {'name': 'Zeus',
         'avatar': 'img/dota/heroes/zuus.png',
         'ability': [{'id': 5110, 'image': 'img/dota/spellicons/zuus_arc_lightning.png'},
                     {'id': 5111, 'image': 'img/dota/spellicons/zuus_lightning_bolt.png'},
                     {'id': 5112, 'image': 'img/dota/spellicons/zuus_static_field.png'},
                     {'id': 5113, 'image': 'img/dota/spellicons/zuus_thundergods_wrath.png'}]},
    23: {'name': 'Kunkka', 'avatar': 'img/dota/heroes/kunkka.png'},
    25: {'name': 'Lina', 'avatar': 'img/dota/heroes/lina.png'},
    26: {'name': 'Lion', 'avatar': 'img/dota/heroes/lion.png'},
    27: {'name': 'Shadow Shaman',
         'avatar': 'img/dota/heroes/shadow_shaman.png',
         'ability': [{'id': 5078, 'image': 'img/dota/spellicons/shadow_shaman_ether_shock.png'},
                     {'id': 5079, 'image': 'img/dota/spellicons/shadow_shaman_voodoo.png'},
                     {'id': 5080, 'image': 'img/dota/spellicons/shadow_shaman_shackles.png'},
                     {'id': 5081, 'image': 'img/dota/spellicons/shadow_shaman_mass_serpent_ward.png'}]},
    28: {'name': 'Slardar', 'avatar': 'img/dota/heroes/slardar.png'},
    29: {'name': 'Tidehunter',
         'avatar': 'img/dota/heroes/tidehunter.png',
         'ability': [{'id': 5118, 'image': 'img/dota/spellicons/tidehunter_gush.png'},
                     {'id': 5119, 'image': 'img/dota/spellicons/tidehunter_kraken_shell.png'},
                     {'id': 5120, 'image': 'img/dota/spellicons/tidehunter_anchor_smash.png'},
                     {'id': 5121, 'image': 'img/dota/spellicons/tidehunter_ravage.png'}]},
    30: {'name': 'Witch Doctor', 'avatar': 'img/dota/heroes/witch_doctor.png'},
    31: {'name': 'Lich',
         'avatar': 'img/dota/heroes/lich.png',
         'ability': [{'id': 5134, 'image': 'img/dota/spellicons/lich_frost_nova.png'},
                     {'id': 5135, 'image': 'img/dota/spellicons/lich_frost_armor.png'},
                     {'id': 5136, 'image': 'img/dota/spellicons/lich_dark_ritual.png'},
                     {'id': 5137, 'image': 'img/dota/spellicons/lich_chain_frost.png'}]},
    32: {'name': 'Riki',
         'avatar': 'img/dota/heroes/riki.png',
         'ability': [{'id': 5142, 'image': 'img/dota/spellicons/riki_smoke_screen.png'},
                     {'id': 5143, 'image': 'img/dota/spellicons/riki_blink_strike.png'},
                     {'id': 5144, 'image': 'img/dota/spellicons/riki_backstab.png'},
                     {'id': 5145, 'image': 'img/dota/spellicons/riki_permanent_invisibility.png'}]},
    33: {'name': 'Enigma', 'avatar': 'img/dota/heroes/enigma.png'},
    34: {'name': 'Tinker', 'avatar': 'img/dota/heroes/tinker.png'},
    35: {'name': 'Sniper',
         'avatar': 'img/dota/heroes/sniper.png',
         'ability': [{'id': 5154, 'image': 'img/dota/spellicons/sniper_shrapnel.png'},
                     {'id': 5155, 'image': 'img/dota/spellicons/sniper_headshot.png'},
                     {'id': 5156, 'image': 'img/dota/spellicons/sniper_take_aim.png'},
                     {'id': 5157, 'image': 'img/dota/spellicons/sniper_assassinate.png'}]},
    36: {'name': 'Necrophos', 'avatar': 'img/dota/heroes/necrolyte.png'},
    37: {'name': 'Warlock', 'avatar': 'img/dota/heroes/warlock.png'},
    38: {'name': 'Beastmaster', 'avatar': 'img/dota/heroes/beastmaster.png'},
    39: {'name': 'Queen of Pain',
         'avatar': 'img/dota/heroes/queenofpain.png',
         'ability': [{'id': 5173, 'image': 'img/dota/spellicons/queenofpain_shadow_strike.png'},
                     {'id': 5174, 'image': 'img/dota/spellicons/queenofpain_blink.png'},
                     {'id': 5175, 'image': 'img/dota/spellicons/queenofpain_scream_of_pain.png'},
                     {'id': 5176, 'image': 'img/dota/spellicons/queenofpain_sonic_wave.png'}]},
    40: {'name': 'Venomancer',
         'avatar': 'img/dota/heroes/venomancer.png',
         'ability': [{'id': 5178, 'image': 'img/dota/spellicons/venomancer_venomous_gale.png'},
                     {'id': 5179, 'image': 'img/dota/spellicons/venomancer_poison_sting.png'},
                     {'id': 5180, 'image': 'img/dota/spellicons/venomancer_plague_ward.png'},
                     {'id': 5181, 'image': 'img/dota/spellicons/venomancer_poison_nova.png'}]},
    41: {'name': 'Faceless Void',
         'avatar': 'img/dota/heroes/faceless_void.png',
         'ability': [{'id': 5182, 'image': 'img/dota/spellicons/faceless_void_time_walk.png'},
                     {'id': 5183, 'image': 'img/dota/spellicons/faceless_void_backtrack.png'},
                     {'id': 5184, 'image': 'img/dota/spellicons/faceless_void_time_lock.png'},
                     {'id': 5185, 'image': 'img/dota/spellicons/faceless_void_chronosphere.png'}]},
    42: {'name': 'Wraith King', 'avatar': 'img/dota/heroes/wraith_king.png'},
    43: {'name': 'Death Prophet',
         'avatar': 'img/dota/heroes/death_prophet.png',
         'ability': [{'id': 5090, 'image': 'img/dota/spellicons/death_prophet_carrion_swarm.png'},
                     {'id': 5091, 'image': 'img/dota/spellicons/death_prophet_silence.png'},
                     {'id': 5092, 'image': 'img/dota/spellicons/death_prophet_witchcraft.png'},
                     {'id': 5093, 'image': 'img/dota/spellicons/death_prophet_exorcism.png'}]},
    44: {'name': 'Phantom Assassin',
         'avatar': 'img/dota/heroes/phantom_assassin.png',
         'ability': [{'id': 5190, 'image': 'img/dota/spellicons/phantom_assassin_stifling_dagger.png'},
                     {'id': 5191, 'image': 'img/dota/spellicons/phantom_assassin_phantom_strike.png'},
                     {'id': 5192, 'image': 'img/dota/spellicons/phantom_assassin_blur.png'},
                     {'id': 5193, 'image': 'img/dota/spellicons/phantom_assassin_coup_de_grace.png'}]},
    45: {'name': 'Pugna', 'avatar': 'img/dota/heroes/pugna.png'},
    46: {'name': 'Templar Assassin', 'avatar': 'img/dota/heroes/templar_assassin.png'},
    47: {'name': 'Viper',
         'avatar': 'img/dota/heroes/viper.png',
         'ability': [{'id': 5218, 'image': 'img/dota/spellicons/viper_poison_attack.png'},
                     {'id': 5219, 'image': 'img/dota/spellicons/viper_nethertoxin.png'},
                     {'id': 5220, 'image': 'img/dota/spellicons/viper_corrosive_skin.png'},
                     {'id': 5221, 'image': 'img/dota/spellicons/viper_viper_strike.png'}]},
    48: {'name': 'Luna',
         'avatar': 'img/dota/heroes/luna.png',
         'ability': [{'id': 5222, 'image': 'img/dota/spellicons/luna_lucent_beam.png'},
                     {'id': 5223, 'image': 'img/dota/spellicons/luna_moon_glaive.png'},
                     {'id': 5224, 'image': 'img/dota/spellicons/luna_lunar_blessing.png'},
                     {'id': 5225, 'image': 'img/dota/spellicons/luna_eclipse.png'}]},
    49: {'name': 'Dragon Knight', 'avatar': 'img/dota/heroes/dragon_knight.png'},
    50: {'name': 'Dazzle', 'avatar': 'img/dota/heroes/dazzle.png'},
    51: {'name': 'Clockwerk',
         'avatar': 'img/dota/heroes/rattletrap.png',
         'ability': [{'id': 5237, 'image': 'img/dota/spellicons/rattletrap_battery_assault.png'},
                     {'id': 5238, 'image': 'img/dota/spellicons/rattletrap_power_cogs.png'},
                     {'id': 5239, 'image': 'img/dota/spellicons/rattletrap_rocket_flare.png'},
                     {'id': 5240, 'image': 'img/dota/spellicons/rattletrap_hookshot.png'}]},
    52: {'name': 'Leshrac', 'avatar': 'img/dota/heroes/leshrac.png'},
    53: {'name': 'Nature\'s Prophet',
         'avatar': 'img/dota/heroes/furion.png',
         'ability': [{'id': 5245, 'image': 'img/dota/spellicons/furion_sprout.png'},
                     {'id': 5246, 'image': 'img/dota/spellicons/furion_teleportation.png'},
                     {'id': 5247, 'image': 'img/dota/spellicons/furion_force_of_nature.png'},
                     {'id': 5248, 'image': 'img/dota/spellicons/furion_wrath_of_nature.png'}]},
    54: {'name': 'Lifestealer', 'avatar': 'img/dota/heroes/life_stealer.png'},
    55: {'name': 'Dark Seer', 'avatar': 'img/dota/heroes/dark_seer.png'},
    56: {'name': 'Clinkz',
         'avatar': 'img/dota/heroes/clinkz.png',
         'ability': [{'id': 5259, 'image': 'img/dota/spellicons/clinkz_strafe.png'},
                     {'id': 5260, 'image': 'img/dota/spellicons/clinkz_searing_arrows.png'},
                     {'id': 5261, 'image': 'img/dota/spellicons/clinkz_wind_walk.png'},
                     {'id': 5262, 'image': 'img/dota/spellicons/clinkz_death_pact.png'}]},
    57: {'name': 'Omniknight',
         'avatar': 'img/dota/heroes/omniknight.png',
         'ability': [{'id': 5263, 'image': 'img/dota/spellicons/omniknight_purification.png'},
                     {'id': 5264, 'image': 'img/dota/spellicons/omniknight_repel.png'},
                     {'id': 5265, 'image': 'img/dota/spellicons/omniknight_degen_aura.png'},
                     {'id': 5266, 'image': 'img/dota/spellicons/omniknight_guardian_angel.png'}]},
    58: {'name': 'Enchantress', 'avatar': 'img/dota/heroes/enchantress.png'},
    59: {'name': 'Huskar', 'avatar': 'img/dota/heroes/huskar.png'},
    60: {'name': 'Night Stalker',
         'avatar': 'img/dota/heroes/night_stalker.png',
         'ability': [{'id': 5275, 'image': 'img/dota/spellicons/night_stalker_void.png'},
                     {'id': 5276, 'image': 'img/dota/spellicons/night_stalker_crippling_fear.png'},
                     {'id': 5277, 'image': 'img/dota/spellicons/night_stalker_hunter_in_the_night.png'},
                     {'id': 5278, 'image': 'img/dota/spellicons/night_stalker_darkness.png'}]},
    61: {'name': 'Broodmother', 'avatar': 'img/dota/heroes/broodmother.png'},
    62: {'name': 'Bounty Hunter',
         'avatar': 'img/dota/heroes/bounty_hunter.png',
         'ability': [{'id': 5285, 'image': 'img/dota/spellicons/bounty_hunter_shuriken_toss.png'},
                     {'id': 5286, 'image': 'img/dota/spellicons/bounty_hunter_jinada.png'},
                     {'id': 5287, 'image': 'img/dota/spellicons/bounty_hunter_wind_walk.png'},
                     {'id': 5288, 'image': 'img/dota/spellicons/bounty_hunter_track.png'}]},
    63: {'name': 'Weaver',
         'avatar': 'img/dota/heroes/weaver.png',
         'ability': [{'id': 5289, 'image': 'img/dota/spellicons/weaver_the_swarm.png'},
                     {'id': 5290, 'image': 'img/dota/spellicons/weaver_shukuchi.png'},
                     {'id': 5291, 'image': 'img/dota/spellicons/weaver_geminate_attack.png'},
                     {'id': 5292, 'image': 'img/dota/spellicons/weaver_time_lapse.png'}]},
    64: {'name': 'Jakiro', 'avatar': 'img/dota/heroes/jakiro.png'},
    65: {'name': 'Batrider', 'avatar': 'img/dota/heroes/batrider.png'},
    66: {'name': 'Chen', 'avatar': 'img/dota/heroes/chen.png'},
    67: {'name': 'Spectre', 'avatar': 'img/dota/heroes/spectre.png'},
    68: {'name': 'Ancient Apparition', 'avatar': 'img/dota/heroes/ancient_apparition.png'},
    69: {'name': 'Doom Bringer', 'avatar': 'img/dota/heroes/doom_bringer.png'},
    70: {'name': 'Ursa',
         'avatar': 'img/dota/heroes/ursa.png',
         'ability': [{'id': 5357, 'image': 'img/dota/spellicons/ursa_earthshock.png'},
                     {'id': 5358, 'image': 'img/dota/spellicons/ursa_overpower.png'},
                     {'id': 5359, 'image': 'img/dota/spellicons/ursa_fury_swipes.png'},
                     {'id': 5360, 'image': 'img/dota/spellicons/ursa_enrage.png'}]},
    71: {'name': 'Spirit Breaker',
         'avatar': 'img/dota/heroes/spirit_breaker.png',
         'ability': [{'id': 5353, 'image': 'img/dota/spellicons/spirit_breaker_charge_of_darkness.png'},
                     {'id': 5354, 'image': 'img/dota/spellicons/spirit_breaker_empowering_haste.png'},
                     {'id': 5355, 'image': 'img/dota/spellicons/spirit_breaker_greater_bash.png'},
                     {'id': 5356, 'image': 'img/dota/spellicons/spirit_breaker_nether_strike.png'}]},
    72: {'name': 'Gyrocopter',
         'avatar': 'img/dota/heroes/gyrocopter.png',
         'ability': [{'id': 5361, 'image': 'img/dota/spellicons/gyrocopter_rocket_barrage.png'},
                     {'id': 5362, 'image': 'img/dota/spellicons/gyrocopter_homing_missile.png'},
                     {'id': 5363, 'image': 'img/dota/spellicons/gyrocopter_flak_cannon.png'},
                     {'id': 5364, 'image': 'img/dota/spellicons/gyrocopter_call_down.png'}]},
    73: {'name': 'Alchemist',
         'avatar': 'img/dota/heroes/alchemist.png',
         'ability': [{'id': 5365, 'image': 'img/dota/spellicons/alchemist_acid_spray.png'},
                     {'id': 5366, 'image': 'img/dota/spellicons/alchemist_unstable_concoction.png'},
                     {'id': 5368, 'image': 'img/dota/spellicons/alchemist_goblins_greed.png'},
                     {'id': 5369, 'image': 'img/dota/spellicons/alchemist_chemical_rage.png'}]},
    74: {'name': 'Invoker',
         'avatar': 'img/dota/heroes/invoker.png',
         'ability': [{'id': 5370, 'image': 'img/dota/spellicons/invoker_quas.png'},
                     {'id': 5371, 'image': 'img/dota/spellicons/invoker_wex.png'},
                     {'id': 5372, 'image': 'img/dota/spellicons/invoker_exort.png'},
                     {'id': 5375, 'image': 'img/dota/spellicons/invoker_invoke.png'}]},
    75: {'name': 'Silencer',
         'avatar': 'img/dota/heroes/silencer.png',
         'ability': [{'id': 5377, 'image': 'img/dota/spellicons/silencer_curse_of_the_silent.png'},
                     {'id': 5378, 'image': 'img/dota/spellicons/silencer_glaives_of_wisdom.png'},
                     {'id': 5379, 'image': 'img/dota/spellicons/silencer_last_word.png'},
                     {'id': 5380, 'image': 'img/dota/spellicons/silencer_global_silence.png'}]},
    76: {'name': 'Outworld Devourer', 'avatar': 'img/dota/heroes/obsidian_destroyer.png'},
    77: {'name': 'Lycan', 'avatar': 'img/dota/heroes/lycan.png'},
    78: {'name': 'Brewmaster', 'avatar': 'img/dota/heroes/brewmaster.png'},
    79: {'name': 'Shadow Demon', 'avatar': 'img/dota/heroes/shadow_demon.png'},
    80: {'name': 'Lone Druid', 'avatar': 'img/dota/heroes/lone_druid.png'},
    81: {'name': 'Chaos Knight', 'avatar': 'img/dota/heroes/chaos_knight.png'},
    82: {'name': 'Meepo', 'avatar': 'img/dota/heroes/meepo.png'},
    83: {'name': 'Treant Protector',
         'avatar': 'img/dota/heroes/treant.png',
         'ability': [{'id': 5434, 'image': 'img/dota/spellicons/treant_natures_guise.png'},
                     {'id': 5435, 'image': 'img/dota/spellicons/treant_leech_seed.png'},
                     {'id': 5436, 'image': 'img/dota/spellicons/treant_living_armor.png'},
                     {'id': 5437, 'image': 'img/dota/spellicons/treant_overgrowth.png'}]},
    84: {'name': 'Ogre Magi',
         'avatar': 'img/dota/heroes/ogre_magi.png',
         'ability': [{'id': 5438, 'image': 'img/dota/spellicons/ogre_magi_fireblast.png'},
                     {'id': 5439, 'image': 'img/dota/spellicons/ogre_magi_ignite.png'},
                     {'id': 5440, 'image': 'img/dota/spellicons/ogre_magi_bloodlust.png'},
                     {'id': 5441, 'image': 'img/dota/spellicons/ogre_magi_multicast.png'}]},
    85: {'name': 'Undying', 'avatar': 'img/dota/heroes/undying.png'},
    86: {'name': 'Rubick', 'avatar': 'img/dota/heroes/rubick.png'},
    87: {'name': 'Disruptor', 'avatar': 'img/dota/heroes/disruptor.png'},
    88: {'name': 'Nyx Assassin',
         'avatar': 'img/dota/heroes/nyx_assassin.png',
         'ability': [{'id': 5462, 'image': 'img/dota/spellicons/nyx_assassin_impale.png'},
                     {'id': 5463, 'image': 'img/dota/spellicons/nyx_assassin_mana_burn.png'},
                     {'id': 5464, 'image': 'img/dota/spellicons/nyx_assassin_spiked_carapace.png'},
                     {'id': 5465, 'image': 'img/dota/spellicons/nyx_assassin_vendetta.png'}]},
    89: {'name': 'Naga Siren',
         'avatar': 'img/dota/heroes/naga_siren.png',
         'ability': [{'id': 5467, 'image': 'img/dota/spellicons/naga_siren_mirror_image.png'},
                     {'id': 5468, 'image': 'img/dota/spellicons/naga_siren_ensnare.png'},
                     {'id': 5469, 'image': 'img/dota/spellicons/naga_siren_rip_tide.png'},
                     {'id': 5470, 'image': 'img/dota/spellicons/naga_siren_song_of_the_siren.png'}]},
    90: {'name': 'Keeper of the Light',
         'avatar': 'img/dota/heroes/keeper_of_the_light.png',
         'ability': [{'id': 5471, 'image': 'img/dota/spellicons/keeper_of_the_light_illuminate.png'},
                     {'id': 5472, 'image': 'img/dota/spellicons/keeper_of_the_light_mana_leak.png'},
                     {'id': 5473, 'image': 'img/dota/spellicons/keeper_of_the_light_chakra_magic.png'},
                     {'id': 5474, 'image': 'img/dota/spellicons/keeper_of_the_light_spirit_form.png'}]},
    91: {'name': 'Io', 'avatar': 'img/dota/heroes/wisp.png'},
    92: {'name': 'Visage', 'avatar': 'img/dota/heroes/visage.png'},
    93: {'name': 'Slark',
         'avatar': 'img/dota/heroes/slark.png',
         'ability': [{'id': 5494, 'image': 'img/dota/spellicons/slark_dark_pact.png'},
                     {'id': 5495, 'image': 'img/dota/spellicons/slark_pounce.png'},
                     {'id': 5496, 'image': 'img/dota/spellicons/slark_essence_shift.png'},
                     {'id': 5497, 'image': 'img/dota/spellicons/slark_shadow_dance.png'}]},
    94: {'name': 'Medusa',
         'avatar': 'img/dota/heroes/medusa.png',
         'ability': [{'id': 5504, 'image': 'img/dota/spellicons/medusa_split_shot.png'},
                     {'id': 5505, 'image': 'img/dota/spellicons/medusa_mystic_snake.png'},
                     {'id': 5506, 'image': 'img/dota/spellicons/medusa_mana_shield.png'},
                     {'id': 5507, 'image': 'img/dota/spellicons/medusa_stone_gaze.png'}]},
    95: {'name': 'Troll Warlord',
         'avatar': 'img/dota/heroes/troll_warlord.png',
         'ability': [{'id': 5508, 'image': 'img/dota/spellicons/troll_warlord_berserkers_rage.png'},
                     {'id': 5509, 'image': 'img/dota/spellicons/troll_warlord_whirling_axes_ranged.png'},
                     {'id': 5510, 'image': 'img/dota/spellicons/troll_warlord_whirling_axes_melee.png'},
                     {'id': 5511, 'image': 'img/dota/spellicons/troll_warlord_fervor.png'},
                     {'id': 5512, 'image': 'img/dota/spellicons/troll_warlord_battle_trance.png'}]},
    96: {'name': 'Centaur Warrunner',
         'avatar': 'img/dota/heroes/centaur.png',
         'ability': [{'id': 5514, 'image': 'img/dota/spellicons/centaur_hoof_stomp.png'},
                     {'id': 5515, 'image': 'img/dota/spellicons/centaur_double_edge.png'},
                     {'id': 5516, 'image': 'img/dota/spellicons/centaur_return.png'},
                     {'id': 5517, 'image': 'img/dota/spellicons/centaur_stampede.png'}]},
    97: {'name': 'Magnus',
         'avatar': 'img/dota/heroes/magnataur.png',
         'ability': [{'id': 5518, 'image': 'img/dota/spellicons/magnataur_shockwave.png'},
                     {'id': 5519, 'image': 'img/dota/spellicons/magnataur_empower.png'},
                     {'id': 5520, 'image': 'img/dota/spellicons/magnataur_skewer.png'},
                     {'id': 5521, 'image': 'img/dota/spellicons/magnataur_reverse_polarity.png'}]},
    98: {'name': 'Timbersaw',
         'avatar': 'img/dota/heroes/shredder.png',
         'ability': [{'id': 5524, 'image': 'img/dota/spellicons/shredder_whirling_death.png'},
                     {'id': 5525, 'image': 'img/dota/spellicons/shredder_timber_chain.png'},
                     {'id': 5526, 'image': 'img/dota/spellicons/shredder_reactive_armor.png'},
                     {'id': 5527, 'image': 'img/dota/spellicons/shredder_chakram.png'}]},
    99: {'name': 'Bristleback',
         'avatar': 'img/dota/heroes/bristleback.png',
         'ability': [{'id': 5548, 'image': 'img/dota/spellicons/bristleback_viscous_nasal_goo.png'},
                     {'id': 5549, 'image': 'img/dota/spellicons/bristleback_quill_spray.png'},
                     {'id': 5550, 'image': 'img/dota/spellicons/bristleback_bristleback.png'},
                     {'id': 5551, 'image': 'img/dota/spellicons/bristleback_warpath.png'}]},
    100: {'name': 'Tusk',
          'avatar': 'img/dota/heroes/tusk.png',
          'ability': [{'id': 5565, 'image': 'img/dota/spellicons/tusk_ice_shards.png'},
                      {'id': 5566, 'image': 'img/dota/spellicons/tusk_snowball.png'},
                      {'id': 5567, 'image': 'img/dota/spellicons/tusk_frozen_sigil.png'},
                      {'id': 5568, 'image': 'img/dota/spellicons/tusk_walrus_punch.png'}]},
    101: {'name': 'Skywrath Mage',
          'avatar': 'img/dota/heroes/skywrath_mage.png',
          'ability': [{'id': 5581, 'image': 'img/dota/spellicons/skywrath_mage_arcane_bolt.png'},
                      {'id': 5582, 'image': 'img/dota/spellicons/skywrath_mage_concussive_shot.png'},
                      {'id': 5583, 'image': 'img/dota/spellicons/skywrath_mage_ancient_seal.png'},
                      {'id': 5584, 'image': 'img/dota/spellicons/skywrath_mage_mystic_flare.png'}]},
    102: {'name': 'Abaddon',
          'avatar': 'img/dota/heroes/abaddon.png',
          'ability': [{'id': 5585, 'image': 'img/dota/spellicons/abaddon_death_coil.png'},
                      {'id': 5586, 'image': 'img/dota/spellicons/abaddon_aphotic_shield.png'},
                      {'id': 5587, 'image': 'img/dota/spellicons/abaddon_frostmourne.png'},
                      {'id': 5588, 'image': 'img/dota/spellicons/abaddon_borrowed_time.png'}]},
    103: {'name': 'Elder Titan',
          'avatar': 'img/dota/heroes/elder_titan.png',
          'ability': [{'id': 5589, 'image': 'img/dota/spellicons/elder_titan_echo_stomp.png'},
                      {'id': 5591, 'image': 'img/dota/spellicons/elder_titan_ancestral_spirit.png'},
                      {'id': 5593, 'image': 'img/dota/spellicons/elder_titan_natural_order.png'},
                      {'id': 5594, 'image': 'img/dota/spellicons/elder_titan_earth_splitter.png'}]},
    104: {'name': 'Legion Commander',
          'avatar': 'img/dota/heroes/legion_commander.png',
          'ability': [{'id': 5595, 'image': 'img/dota/spellicons/legion_commander_overwhelming_odds.png'},
                      {'id': 5596, 'image': 'img/dota/spellicons/legion_commander_press_the_attack.png'},
                      {'id': 5597, 'image': 'img/dota/spellicons/legion_commander_moment_of_courage.png'},
                      {'id': 5598, 'image': 'img/dota/spellicons/legion_commander_duel.png'}]},
    106: {'name': 'Ember Spirit',
          'avatar': 'img/dota/heroes/ember_spirit.png',
          'ability': [{'id': 5603, 'image': 'img/dota/spellicons/ember_spirit_searing_chains.png'},
                      {'id': 5604, 'image': 'img/dota/spellicons/ember_spirit_sleight_of_fist.png'},
                      {'id': 5605, 'image': 'img/dota/spellicons/ember_spirit_flame_guard.png'},
                      {'id': 5606, 'image': 'img/dota/spellicons/ember_spirit_fire_remnant.png'}]},
    107: {'name': 'Earth Spirit',
          'avatar': 'img/dota/heroes/earth_spirit.png',
          'ability': [{'id': 5608, 'image': 'img/dota/spellicons/earth_spirit_boulder_smash.png'},
                      {'id': 5609, 'image': 'img/dota/spellicons/earth_spirit_rolling_boulder.png'},
                      {'id': 5610, 'image': 'img/dota/spellicons/earth_spirit_geomagnetic_grip.png'},
                      {'id': 5612, 'image': 'img/dota/spellicons/earth_spirit_magnetize.png'}]},
    109: {'name': 'Terrorblade',
          'avatar': 'img/dota/heroes/terrorblade.png',
          'ability': [{'id': 5619, 'image': 'img/dota/spellicons/terrorblade_reflection.png'},
                      {'id': 5620, 'image': 'img/dota/spellicons/terrorblade_conjure_image.png'},
                      {'id': 5621, 'image': 'img/dota/spellicons/terrorblade_metamorphosis.png'},
                      {'id': 5622, 'image': 'img/dota/spellicons/terrorblade_sunder.png'}]},
    110: {'name': 'Phoenix',
          'avatar': 'img/dota/heroes/phoenix.png',
          'ability': [{'id': 5623, 'image': 'img/dota/spellicons/phoenix_icarus_dive.png'},
                      {'id': 5625, 'image': 'img/dota/spellicons/phoenix_fire_spirits.png'},
                      {'id': 5626, 'image': 'img/dota/spellicons/phoenix_sun_ray.png'},
                      {'id': 5630, 'image': 'img/dota/spellicons/phoenix_supernova.png'}]}
}