#!/usr/bin/env python3
# All right reserved 2013
# Description: Dota 2 Library (Items)
# URL: http://github.com/Lardjo

items = {

    0: {'avatar': 'holder.js/60x45/text:Empty'},
    1: {'name': 'Blink Dagger', 'avatar': 'img/dota/items/blink_dagger.png'},
    2: {'name': 'Blades of Attack', 'avatar': 'img/dota/items/blades_of_attack.png'},
    3: {'name': 'Broadsword', 'avatar': 'img/dota/items/broadsword.png'},
    4: {'name': 'Chainmail', 'avatar': 'img/dota/items/chainmail.png'},
    5: {'name': 'Claymore', 'avatar': 'img/dota/items/claymore.png'},
    6: {'name': 'Helm of Iron Will', 'avatar': 'img/dota/items/helm_of_iron_will.png'},
    7: {'name': 'Javelin', 'avatar': 'img/dota/items/javelin.png'},
    8: {'name': 'Mithril Hammer', 'avatar': 'img/dota/items/mithril_hammer.png'},
    9: {'name': 'Platemail', 'avatar': 'img/dota/items/platemail.png'},
    10: {'name': 'Quarterstaff', 'avatar': 'img/dota/items/quarterstaff.png'},
    11: {'name': 'Quelling Blade', 'avatar': 'img/dota/items/quelling_blade.png'},
    12: {'name': 'Ring of Protection', 'avatar': 'img/dota/items/ring_of_protection.png'},
    13: {'name': 'Gauntlets of Strength', 'avatar': 'img/dota/items/gauntlets_of_strength.png'},
    14: {'name': 'Slippers of Agility', 'avatar': 'img/dota/items/slippers_of_agility.png'},
    15: {'name': 'Mantle of Intelligence', 'avatar': 'img/dota/items/mantle_of_intelligence.png'},
    16: {'name': 'Iron Branch', 'avatar': 'img/dota/items/iron_branch.png'},
    17: {'name': 'Belt of Strength', 'avatar': 'img/dota/items/belt_of_strength.png'},
    18: {'name': 'Band of Elvenskin', 'avatar': 'img/dota/items/band_of_elvenskin.png'},
    19: {'name': 'Robe of the Magi', 'avatar': 'img/dota/items/robe_of_the_magi.png'},
    20: {'name': 'Circlet', 'avatar': 'img/dota/items/circlet.png'},
    21: {'name': 'Ogre Club', 'avatar': 'img/dota/items/ogre_club.png'},
    22: {'name': 'Blade of Alacrity', 'avatar': 'img/dota/items/blade_of_alacrity.png'},
    23: {'name': 'Staff of Wizardry', 'avatar': 'img/dota/items/staff_of_wizardry.png'},
    24: {'name': 'Ultimate Orb', 'avatar': 'img/dota/items/ultimate_orb.png'},
    25: {'name': 'Gloves of Haste', 'avatar': 'img/dota/items/gloves_of_haste.png'},
    26: {'name': 'Morbid Mask', 'avatar': 'img/dota/items/morbid_mask.png'},
    27: {'name': 'Ring of Regen', 'avatar': 'img/dota/items/ring_of_regen.png'},
    28: {'name': 'Sage\'s Mask', 'avatar': 'img/dota/items/sages_mask.png'},
    29: {'name': 'Boots of Speed', 'avatar': 'img/dota/items/boots_of_speed.png'},
    30: {'name': 'Gem of True Sight', 'avatar': 'img/dota/items/gem_of_true_sight.png'},
    31: {'name': 'Cloak', 'avatar': 'img/dota/items/cloak.png'},
    32: {'name': 'Talisman of Evasion', 'avatar': 'img/dota/items/talisman_of_evasion.png'},
    33: {'name': 'Cheese', 'avatar': 'img/dota/items/cheese.png'},
    34: {'name': 'Magic Stick', 'avatar': 'img/dota/items/magic_stick.png'},
    35: {'name': 'Recipe: Magic Wand', 'avatar': 'img/dota/items/recipe_scroll.png'},
    36: {'name': 'Magic Wand', 'avatar': 'img/dota/items/magic_wand.png'},
    37: {'name': 'Ghost Scepter', 'avatar': 'img/dota/items/ghost_scepter.png'},
    38: {'name': 'Clarity', 'avatar': 'img/dota/items/clarity.png'},
    39: {'name': 'Healing Salve', 'avatar': 'img/dota/items/healing_salve.png'},
    40: {'name': 'Dust of Appearance', 'avatar': 'img/dota/items/dust_of_appearance.png'},
    41: {'name': 'Bottle', 'avatar': 'img/dota/items/bottle.png'},
    42: {'name': 'Observer Ward', 'avatar': 'img/dota/items/observer_ward.png'},
    43: {'name': 'Sentry Ward', 'avatar': 'img/dota/items/sentry_ward.png'},
    44: {'name': 'Tango', 'avatar': 'img/dota/items/tango.png'},
    45: {'name': 'Courier', 'avatar': 'img/dota/items/courier.png'},
    46: {'name': 'Teleport Scroll', 'avatar': 'img/dota/items/town_portal_scroll.png'},
    48: {'name': 'Travel Boots', 'avatar': 'img/dota/items/boots_of_travel.png'},
    50: {'name': 'Phase Boots', 'avatar': 'img/dota/items/phase_boots.png'},
    51: {'name': 'Demon Edge', 'avatar': 'img/dota/items/demon_edge.png'},
    52: {'name': 'Eaglesong', 'avatar': 'img/dota/items/eaglesong.png'},
    53: {'name': 'Reaver', 'avatar': 'img/dota/items/reaver.png'},
    54: {'name': 'Sacred Relic', 'avatar': 'img/dota/items/sacred_relic.png'},
    55: {'name': 'Hyperstone', 'avatar': 'img/dota/items/hyperstone.png'},
    56: {'name': 'Ring of Health', 'avatar': 'img/dota/items/ring_of_health.png'},
    57: {'name': 'Void Stone', 'avatar': 'img/dota/items/void_stone.png'},
    58: {'name': 'Mystic Staff', 'avatar': 'img/dota/items/mystic_staff.png'},
    59: {'name': 'Energy Booster', 'avatar': 'img/dota/items/energy_booster.png'},
    60: {'name': 'Point Booster', 'avatar': 'img/dota/items/point_booster.png'},
    61: {'name': 'Vitality Booster', 'avatar': 'img/dota/items/vitality_booster.png'},
    63: {'name': 'Power Treads', 'avatar': 'img/dota/items/power_treads.png'},
    65: {'name': 'Hand of Midas', 'avatar': 'img/dota/items/hand_of_midas.png'},
    67: {'name': 'Oblivion Staff', 'avatar': 'img/dota/items/oblivion_staff.png'},
    69: {'name': 'Perseverance', 'avatar': 'img/dota/items/perseverance.png'},
    71: {'name': 'Poor Man\'s Shield', 'avatar': 'img/dota/items/poor_mans_shield.png'},
    73: {'name': 'Bracer', 'avatar': 'img/dota/items/bracer.png'},
    75: {'name': 'Wraith Band', 'avatar': 'img/dota/items/wraith_band.png'},
    77: {'name': 'Null Talisman', 'avatar': 'img/dota/items/null_talisman.png'},
    79: {'name': 'Mekansm', 'avatar': 'img/dota/items/mekansm.png'},
    81: {'name': 'Vladmir\'s Offering', 'avatar': 'img/dota/items/vladmirs_offering.png'},
    86: {'name': 'Buckler', 'avatar': 'img/dota/items/buckler.png'},
    88: {'name': 'Ring of Basilius', 'avatar': 'img/dota/items/ring_of_basilius.png'},
    90: {'name': 'Pipe of Insight', 'avatar': 'img/dota/items/pipe_of_insight.png'},
    92: {'name': 'Urn of Shadows', 'avatar': 'img/dota/items/urn_of_shadows.png'},
    94: {'name': 'Headdress', 'avatar': 'img/dota/items/headdress.png'},
    96: {'name': 'Scythe of Vyse', 'avatar': 'img/dota/items/scythe_of_vyse.png'},
    98: {'name': 'Orchid Malevolence', 'avatar': 'img/dota/items/orchid_malevolence.png'},
    100: {'name': 'Euls Scepter of Divinity', 'avatar': 'img/dota/items/euls_scepter_of_divinity.png'},
    102: {'name': 'Force Staff', 'avatar': 'img/dota/items/force_staff.png'},
    104: {'name': 'Dagon: Level 1', 'avatar': 'img/dota/items/dagon_1.png'},
    108: {'name': 'Aghanim\'s Scepter', 'avatar': 'img/dota/items/aghanims_scepter.png'},
    110: {'name': 'Refresher Orb', 'avatar': 'img/dota/items/refresher_orb.png'},
    112: {'name': 'Assault Cuirass', 'avatar': 'img/dota/items/assault_cuirass.png'},
    114: {'name': 'Heart of Tarrasque', 'avatar': 'img/dota/items/heart_of_tarrasque.png'},
    117: {'name': 'Aegis', 'avatar': 'img/dota/items/aegis.png'},
    119: {'name': 'Shiva\'s Guard', 'avatar': 'img/dota/items/shivas_guard.png'},
    116: {'name': 'Black King Bar', 'avatar': 'img/dota/items/black_king_bar.png'},
    121: {'name': 'Bloodstone', 'avatar': 'img/dota/items/bloodstone.png'},
    122: {'name': 'Recipe: Linken\'s Sphere', 'avatar': 'img/dota/items/recipe_scroll.png'},
    123: {'name': 'Linken\'s Sphere', 'avatar': 'img/dota/items/linkens_sphere.png'},
    125: {'name': 'Vanguard', 'avatar': 'img/dota/items/vanguard.png'},
    127: {'name': 'Blade Mail', 'avatar': 'img/dota/items/blade_mail.png'},
    131: {'name': 'Hood of Defiance', 'avatar': 'img/dota/items/hood_of_defiance.png'},
    133: {'name': 'Divine Rapier', 'avatar': 'img/dota/items/divine_rapier.png'},
    135: {'name': 'Monkey King Bar', 'avatar': 'img/dota/items/monkey_king_bar.png'},
    137: {'name': 'Radiance', 'avatar': 'img/dota/items/radiance.png'},
    139: {'name': 'Butterfly', 'avatar': 'img/dota/items/butterfly.png'},
    140: {'name': 'Recipe: Daedalus', 'avatar': 'img/dota/items/recipe_scroll.png'},
    141: {'name': 'Daedalus', 'avatar': 'img/dota/items/daedalus.png'},
    143: {'name': 'Basher', 'avatar': 'img/dota/items/skull_basher.png'},
    145: {'name': 'Battlefury', 'avatar': 'img/dota/items/battle_fury.png'},
    147: {'name': 'Manta', 'avatar': 'img/dota/items/manta_style.png'},
    149: {'name': 'Crystalys', 'avatar': 'img/dota/items/crystalys.png'},
    151: {'name': 'Armlet of Mordiggian', 'avatar': 'img/dota/items/armlet_of_mordiggian.png'},
    152: {'name': 'Shadow Blade', 'avatar': 'img/dota/items/shadow_blade.png'},
    154: {'name': 'Sange and Yasha', 'avatar': 'img/dota/items/sange_and_yasha.png'},
    156: {'name': 'Satanic', 'avatar': 'img/dota/items/satanic.png'},
    158: {'name': 'Mjollnir', 'avatar': 'img/dota/items/mjollnir.png'},
    160: {'name': 'Eye of Skadi', 'avatar': 'img/dota/items/eye_of_skadi.png'},
    162: {'name': 'Sange', 'avatar': 'img/dota/items/sange.png'},
    164: {'name': 'Helm of the Dominator', 'avatar': 'img/dota/items/helm_of_the_dominator.png'},
    166: {'name': 'Maelstrom', 'avatar': 'img/dota/items/maelstrom.png'},
    167: {'name': 'Recipe: Desolator', 'avatar': 'img/dota/items/recipe_scroll.png'},
    168: {'name': 'Desolator', 'avatar': 'img/dota/items/desolator.png'},
    170: {'name': 'Yasha', 'avatar': 'img/dota/items/yasha.png'},
    172: {'name': 'Mask of Madness', 'avatar': 'img/dota/items/mask_of_madness.png'},
    174: {'name': 'Diffusal Blade: Level 1', 'avatar': 'img/dota/items/diffusal_blade_1.png'},
    176: {'name': 'Ethereal Blade', 'avatar': 'img/dota/items/ethereal_blade.png'},
    178: {'name': 'Soul Ring', 'avatar': 'img/dota/items/soul_ring.png'},
    180: {'name': 'Arcane Boots', 'avatar': 'img/dota/items/arcane_boots.png'},
    181: {'name': 'Orb of Venom', 'avatar': 'img/dota/items/orb_of_venom.png'},
    182: {'name': 'Stout Shield', 'avatar': 'img/dota/items/stout_shield.png'},
    185: {'name': 'Drum of Endurance', 'avatar': 'img/dota/items/drum_of_endurance.png'},
    187: {'name': 'Medallion of Courage', 'avatar': 'img/dota/items/medallion_of_courage.png'},
    188: {'name': 'Smoke of Deceit', 'avatar': 'img/dota/items/smoke_of_deceit.png'},
    190: {'name': 'Veil of Discord', 'avatar': 'img/dota/items/veil_of_discord.png'},
    193: {'name': 'Necronomicon: Level 2', 'avatar': 'img/dota/items/necronomicon_2.png'},
    194: {'name': 'Necronomicon', 'avatar': 'img/dota/items/necronomicon.png'},
    196: {'name': 'Diffusal Blade: Level 2', 'avatar': 'img/dota/items/diffusal_blade.png'},
    201: {'name': 'Dagon: Level 2', 'avatar': 'img/dota/items/dagon_2.png'},
    202: {'name': 'Dagon: Level 3', 'avatar': 'img/dota/items/dagon_3.png'},
    203: {'name': 'Dagon: Level 4', 'avatar': 'img/dota/items/dagon_4.png'},
    204: {'name': 'Dagon: Level 5', 'avatar': 'img/dota/items/dagon.png'},
    206: {'name': 'Rod of Atos', 'avatar': 'img/dota/items/rod_of_atos.png'},
    208: {'name': 'Abyssal Blade', 'avatar': 'img/dota/items/abyssal_blade.png'},
    210: {'name': 'Heaven\'s Halberd', 'avatar': 'img/dota/items/heavens_halberd.png'},
    212: {'name': 'Ring of Aquila', 'avatar': 'img/dota/items/ring_of_aquila.png'},
    214: {'name': 'Tranquil Boots', 'avatar': 'img/dota/items/tranquil_boots.png'},
    215: {'name': 'Shadow Amulet', 'avatar': 'img/dota/items/shadow_amulet.png'},
    229: {'name': 'Xmas Stocking', 'avatar': 'img/dota/items/xmas_stocking.png'},
    230: {'name': 'Speed Skates', 'avatar': 'img/dota/items/speed_skates.png'},
    231: {'name': 'Fruit-bit Cake', 'avatar': 'img/dota/items/fruit-bit_cake.png'},
    232: {'name': 'Wizard Cookie', 'avatar': 'img/dota/items/wizard_cookie.png'},
    233: {'name': 'Cocoa with Marshmallows', 'avatar': 'img/dota/items/cocoa.png'},
    234: {'name': 'Clove Studded Ham', 'avatar': 'img/dota/items/clove_studded_ham.png'},
    235: {'name': 'Greevil Whistle', 'avatar': 'img/dota/items/greevil_whistle.png'},
    236: {'name': 'Kringle', 'avatar': 'img/dota/items/kringle.png'}

}