# -*- coding: utf-8 -*-
# Welcome
# Dota 2 Heroes and Items Library
# Last update: March, 8, 2013

Heroes = {
	
	1: {'name': 'Antimage', 'avatar': 'anti_mage.jpg'},
	2: {'name': 'Axe', 'avatar': 'static/img/dota2heroes/axe.png'},
	3: {'name': 'Ban', 'avatar': 'ban.jpg'},
	4: {'name': 'Bloodseeker', 'avatar': 'bloodseeker.jpg'},
	5: {'name': 'Crystal Maiden', 'avatar': 'crystal_maiden.jpg'},
	6: {'name': 'Drow Ranger', 'avatar': 'drow_ranger.jpg'},
	7: {'name': 'Earthshaker', 'avatar': 'earthshaker.jpg'},
	8: {'name': 'Juggernaut', 'avatar': 'juggernaut.jpg'},
	9: {'name': 'Mirana', 'avatar': 'mirana.jpg'},
	10: {'name': 'Morphling', 'avatar': 'morphling.jpg'},
	11: {'name': 'Shadow Fiend', 'avatar': 'shadow_fiend.jpg'},
	12: {'name': 'Phantom Lancer', 'avatar': 'phantom_lancer.jpg'},
	13: {'name': 'Puck', 'avatar': 'puck.jpg'},
	14: {'name': 'Pudge', 'avatar': 'pudge.jpg'},
	15: {'name': 'Razor', 'avatar': 'razor.jpg'},
	16: {'name': 'Sand King', 'avatar': 'sand_king.jpg'},
	17: {'name': 'Storm Spirit', 'avatar': 'storm_spirit.jpg'},
	18: {'name': 'Sven', 'avatar': 'sven.jpg'},
	19: {'name': 'Tiny', 'avatar': 'tiny.jpg'},
	20: {'name': 'Vengeful Spirit', 'avatar': 'vengeful_spirit.jpg'},
	21: {'name': 'Windrunner', 'avatar': 'windrunner.jpg'},
	22: {'name': 'Zeus', 'avatar': 'zeus.jpg'},
	23: {'name': 'Kunkka', 'avatar': 'kunkka.jpg'},
	25: {'name': 'Lina', 'avatar': 'static/img/dota2heroes/lina.png'},
	26: {'name': 'Lion', 'avatar': 'lion.jpg'},
	27: {'name': 'Shadow Shaman', 'avatar': 'shadow_shaman.jpg'},
	28: {'name': 'Slardar', 'avatar': 'slardar.jpg'},
	29: {'name': 'Tidehunter', 'avatar': 'tidehunter.jpg'},
	30: {'name': 'Witch Doctor', 'avatar': 'witch_doctor.jpg'},
	31: {'name': 'Lich', 'avatar': 'lich.jpg'},
	32: {'name': 'Riki', 'avatar': 'riki.jpg'},
	33: {'name': 'Enigma', 'avatar': 'enigma.jpg'},
	34: {'name': 'Tinker', 'avatar': 'tinker.jpg'},
	35: {'name': 'Sniper', 'avatar': 'sniper.jpg'},
	36: {'name': 'Necrolyte', 'avatar': 'necrolyte.jpg'},
	37: {'name': 'Warlock', 'avatar': 'warlock.jpg'},
	38: {'name': 'Beastmaster', 'avatar': 'static/img/dota2heroes/beastmaster.png'},
	39: {'name': 'Queen of Pain', 'avatar': 'static/img/dota2heroes/queen_of_pain.png'},
	40: {'name': 'Venomancer', 'avatar': 'venomancer.jpg'},
	41: {'name': 'Faceless Void', 'avatar': 'static/img/dota2heroes/faceless_void.png'},
	42: {'name': 'Skeleton King', 'avatar': 'skeleton_king.jpg'},
	43: {'name': 'Death Prophet', 'avatar': 'death_prophet.jpg'},
	44: {'name': 'Phantom Assassin', 'avatar': 'phantom_assassin.jpg'},
	45: {'name': 'Pugna', 'avatar': 'pugna.jpg'},
	46: {'name': 'Templar Assassin', 'avatar': 'templar_assassin.jpg'},
	47: {'name': 'Viper', 'avatar': 'static/img/dota2heroes/viper.png'},
	48: {'name': 'Luna', 'avatar': 'static/img/dota2heroes/luna.png'},
	49: {'name': 'Dragon Knight', 'avatar': 'dragon_knight.jpg'},
	50: {'name': 'Dazzle', 'avatar': 'dazzle.jpg'},
	51: {'name': 'Clockwerk', 'avatar': 'clockwerk.jpg'},
	52: {'name': 'Leshrac', 'avatar': 'leshrac.jpg'},
	53: {'name': 'Natures Prophet', 'avatar': 'natures_prophet.jpg'},
	54: {'name': 'Lifestealer', 'avatar': 'lifestealer.jpg'},
	55: {'name': 'Dark Seer', 'avatar': 'dark_seer.jpg'},
	56: {'name': 'Clinkz', 'avatar': 'static/img/dota2heroes/clinkz.png'},
	57: {'name': 'Omniknight', 'avatar': 'omniknight.jpg'},
	58: {'name': 'Enchantress', 'avatar': 'enchantress.jpg'},
	59: {'name': 'Huskar', 'avatar': 'huskar.jpg'},
	60: {'name': 'Night Stalker', 'avatar': 'static/img/dota2heroes/night_stalker.png'},
	61: {'name': 'Broodmother', 'avatar': 'broodmother.jpg'},
	62: {'name': 'Bounty Hunter', 'avatar': 'bounty_hunter.jpg'},
	63: {'name': 'Weaver', 'avatar': 'weaver.jpg'},
	64: {'name': 'Jakiro', 'avatar': 'jakiro.jpg'},
	65: {'name': 'Batrider', 'avatar': 'batrider.jpg'},
	66: {'name': 'Chen', 'avatar': 'static/img/dota2heroes/chen.png'},
	67: {'name': 'Spectre', 'avatar': 'spectre.jpg'},
	68: {'name': 'Ancient Apparition', 'avatar': 'ancient_aparition.jpg'},
	69: {'name': 'Doom Bringer', 'avatar': 'doom_bringer.jpg'},
	70: {'name': 'Ursa', 'avatar': 'ursa.jpg'},
	71: {'name': 'Spirit Breaker', 'avatar': 'spirit Breaker.jpg'},
	72: {'name': 'Gyrocopter', 'avatar': 'gyrocopter.jpg'},
	73: {'name': 'Alchemist', 'avatar': 'alchemist.jpg'},
	74: {'name': 'Invoker', 'avatar': 'invoker.jpg'},
	75: {'name': 'Silencer', 'avatar': 'silencer.jpg'},
	76: {'name': 'Outworld Destroyer', 'avatar': 'outworld_destroyer.jpg'},
	77: {'name': 'Lycanthrope', 'avatar': 'lycanthrope.jpg'},
	78: {'name': 'Brewmaster', 'avatar': 'brewmaster.jpg'},
	79: {'name': 'Shadow Demon', 'avatar': 'shadow_demon.jpg'},
	80: {'name': 'Lone Druid', 'avatar': 'lone_druid.jpg'},
	81: {'name': 'Chaos Knight', 'avatar': 'chaos_knight.jpg'},
	82: {'name': 'Meepo', 'avatar': 'meepo.jpg'},
	83: {'name': 'Treant Protector', 'avatar': 'treant_protector.jpg'},
	84: {'name': 'Ogre Magi', 'avatar': 'ogre_magi.jpg'},
	85: {'name': 'Undying', 'avatar': 'undying.jpg'},
	86: {'name': 'Rubick', 'avatar': 'rubick.jpg'},
	87: {'name': 'Disruptor', 'avatar': 'disruptor.jpg'},
	88: {'name': 'Nyx Assassin', 'avatar': 'nyx_assassin.jpg'},
	89: {'name': 'Naga Siren', 'avatar': 'naga_siren.jpg'},
	90: {'name': 'Keeper of the Light', 'avatar': 'keeper_of_the_light.jpg'},
	91: {'name': 'Wisp', 'avatar': 'wisp.jpg'},
	92: {'name': 'Visage', 'avatar': 'visage.jpg'},
	93: {'name': 'Slark', 'avatar': 'slark.jpg'},
	94: {'name': 'Medusa', 'avatar': 'medusa.jpg'},
	95: {'name': 'Troll Warlord', 'avatar': 'troll_warlord.jpg'},
	96: {'name': 'Centaur Warrunner', 'avatar': 'centaur_warrunner.jpg'},
	97: {'name': 'Magnus', 'avatar': 'magnus.jpg'},
	98: {'name': 'Timbersaw', 'avatar': 'timbersaw.jpg'},
	100: {'name': 'Tusk', 'avatar': 'tusk.jpg'},

	# Total: 102(98)
	# id24 not found
		
}