# Welcome to Dota 2 Library for Steam Stats
# Link: github.com/Lardjo
# Last update: March 16, 2013
# All Right Reserved (c) 2013

GameMode = {
	
	1: {'name': 'All Pick'},
	2: {'name': 'Captains Mode'},
	3: {'name': 'Random Draft'},
	4: {'name': 'Single Draft'},
	5: {'name': 'All Random'}
	
}

Cluster = {
	
	111: {'name': 'US West'},
	121: {'name': 'US East'},
	122: {'name': 'US East'},
	131: {'name': 'Europe West'},
	132: {'name': 'Europe West'},
	133: {'name': 'Europe West'},
	151: {'name': 'Southeast Asia'},
	152: {'name': 'Southeast Asia'},
	161: {'name': 'China'},
	163: {'name': 'China'},
	171: {'name': 'Australia'},
	181: {'name': 'Russia'},
	182: {'name': 'Russia'},
	191: {'name': 'Europe East'},
	200: {'name': 'South America'}

}

Heroes = {
	
	1: {'name': 'Antimage', 'avatar': 'static/img/dota2heroes/antimage.png'},
	2: {'name': 'Axe', 'avatar': 'static/img/dota2heroes/axe.png'},
	3: {'name': 'Ban', 'avatar': 'static/img/dota2heroes/bane.png'},
	4: {'name': 'Bloodseeker', 'avatar': 'static/img/dota2heroes/bloodseeker.png'},
	5: {'name': 'Crystal Maiden', 'avatar': 'static/img/dota2heroes/crystal_maiden.png'},
	6: {'name': 'Drow Ranger', 'avatar': 'static/img/dota2heroes/drow_ranger.png'},
	7: {'name': 'Earthshaker', 'avatar': 'static/img/dota2heroes/earthshaker.png'},
	8: {'name': 'Juggernaut', 'avatar': 'static/img/dota2heroes/juggernaut.png'},
	9: {'name': 'Mirana', 'avatar': 'static/img/dota2heroes/mirana.png'},
	10: {'name': 'Morphling', 'avatar': 'static/img/dota2heroes/morphling.png'},
	11: {'name': 'Shadow Fiend', 'avatar': 'static/img/dota2heroes/shadow_fiend.png'},
	12: {'name': 'Phantom Lancer', 'avatar': 'static/img/dota2heroes/phantom_lancer.png'},
	13: {'name': 'Puck', 'avatar': 'static/img/dota2heroes/puck.png'},
	14: {'name': 'Pudge', 'avatar': 'static/img/dota2heroes/pudge.png'},
	15: {'name': 'Razor', 'avatar': 'static/img/dota2heroes/razor.png'},
	16: {'name': 'Sand King', 'avatar': 'static/img/dota2heroes/sand_king.png'},
	17: {'name': 'Storm Spirit', 'avatar': 'static/img/dota2heroes/storm_spirit.png'},
	18: {'name': 'Sven', 'avatar': 'static/img/dota2heroes/sven.png'},
	19: {'name': 'Tiny', 'avatar': 'static/img/dota2heroes/tiny.png'},
	20: {'name': 'Vengeful Spirit', 'avatar': 'static/img/dota2heroes/vengeful_spirit.png'},
	21: {'name': 'Windrunner', 'avatar': 'static/img/dota2heroes/windrunner.png'},
	22: {'name': 'Zeus', 'avatar': 'static/img/dota2heroes/zeus.png'},
	23: {'name': 'Kunkka', 'avatar': 'static/img/dota2heroes/kunkka.png'},
	25: {'name': 'Lina', 'avatar': 'static/img/dota2heroes/lina.png'},
	26: {'name': 'Lion', 'avatar': 'static/img/dota2heroes/lion.png'},
	27: {'name': 'Shadow Shaman', 'avatar': 'static/img/dota2heroes/shadow_shaman.png'},
	28: {'name': 'Slardar', 'avatar': 'static/img/dota2heroes/slardar.png'},
	29: {'name': 'Tidehunter', 'avatar': 'static/img/dota2heroes/tidehunter.png'},
	30: {'name': 'Witch Doctor', 'avatar': 'static/img/dota2heroes/witch_doctor.png'},
	31: {'name': 'Lich', 'avatar': 'static/img/dota2heroes/lich.png'},
	32: {'name': 'Riki', 'avatar': 'static/img/dota2heroes/riki.png'},
	33: {'name': 'Enigma', 'avatar': 'static/img/dota2heroes/enigma.png'},
	34: {'name': 'Tinker', 'avatar': 'static/img/dota2heroes/tinker.png'},
	35: {'name': 'Sniper', 'avatar': 'static/img/dota2heroes/sniper.png'},
	36: {'name': 'Necrolyte', 'avatar': 'static/img/dota2heroes/necrolyte.png'},
	37: {'name': 'Warlock', 'avatar': 'static/img/dota2heroes/warlock.png'},
	38: {'name': 'Beastmaster', 'avatar': 'static/img/dota2heroes/beastmaster.png'},
	39: {'name': 'Queen of Pain', 'avatar': 'static/img/dota2heroes/queen_of_pain.png'},
	40: {'name': 'Venomancer', 'avatar': 'static/img/dota2heroes/venomancer.png'},
	41: {'name': 'Faceless Void', 'avatar': 'static/img/dota2heroes/faceless_void.png'},
	42: {'name': 'Skeleton King', 'avatar': 'static/img/dota2heroes/skeleton_king.png'},
	43: {'name': 'Death Prophet', 'avatar': 'static/img/dota2heroes/death_prophet.png'},
	44: {'name': 'Phantom Assassin', 'avatar': 'static/img/dota2heroes/phantom_assassin.png'},
	45: {'name': 'Pugna', 'avatar': 'static/img/dota2heroes/pugna.png'},
	46: {'name': 'Templar Assassin', 'avatar': 'static/img/dota2heroes/templar_assassin.png'},
	47: {'name': 'Viper', 'avatar': 'static/img/dota2heroes/viper.png'},
	48: {'name': 'Luna', 'avatar': 'static/img/dota2heroes/luna.png'},
	49: {'name': 'Dragon Knight', 'avatar': 'static/img/dota2heroes/dragon_knight.png'},
	50: {'name': 'Dazzle', 'avatar': 'static/img/dota2heroes/dazzle.png'},
	51: {'name': 'Clockwerk', 'avatar': 'static/img/dota2heroes/clockwerk.png'},
	52: {'name': 'Leshrac', 'avatar': 'static/img/dota2heroes/leshrac.png'},
	53: {'name': 'Natures Prophet', 'avatar': 'static/img/dota2heroes/nature_prophet.png'},
	54: {'name': 'Lifestealer', 'avatar': 'static/img/dota2heroes/lifestealer.png'},
	55: {'name': 'Dark Seer', 'avatar': 'static/img/dota2heroes/dark_seer.png'},
	56: {'name': 'Clinkz', 'avatar': 'static/img/dota2heroes/clinkz.png'},
	57: {'name': 'Omniknight', 'avatar': 'static/img/dota2heroes/omniknight.png'},
	58: {'name': 'Enchantress', 'avatar': 'static/img/dota2heroes/enchantress.png'},
	59: {'name': 'Huskar', 'avatar': 'static/img/dota2heroes/huskar.png'},
	60: {'name': 'Night Stalker', 'avatar': 'static/img/dota2heroes/night_stalker.png'},
	61: {'name': 'Broodmother', 'avatar': 'static/img/dota2heroes/broodmother.png'},
	62: {'name': 'Bounty Hunter', 'avatar': 'static/img/dota2heroes/bounty_hunter.png'},
	63: {'name': 'Weaver', 'avatar': 'static/img/dota2heroes/weaver.png'},
	64: {'name': 'Jakiro', 'avatar': 'static/img/dota2heroes/jakiro.png'},
	65: {'name': 'Batrider', 'avatar': 'static/img/dota2heroes/batrider.png'},
	66: {'name': 'Chen', 'avatar': 'static/img/dota2heroes/chen.png'},
	67: {'name': 'Spectre', 'avatar': 'static/img/dota2heroes/spectre.png'},
	68: {'name': 'Ancient Apparition', 'avatar': 'static/img/dota2heroes/ancient_aparition.png'},
	69: {'name': 'Doom Bringer', 'avatar': 'static/img/dota2heroes/doom_bringer.png'},
	70: {'name': 'Ursa', 'avatar': 'static/img/dota2heroes/ursa.png'},
	71: {'name': 'Spirit Breaker', 'avatar': 'static/img/dota2heroes/spirit_breaker.png'},
	72: {'name': 'Gyrocopter', 'avatar': 'static/img/dota2heroes/gyrocopter.png'},
	73: {'name': 'Alchemist', 'avatar': 'static/img/dota2heroes/alchemist.png'},
	74: {'name': 'Invoker', 'avatar': 'static/img/dota2heroes/invoker.png'},
	75: {'name': 'Silencer', 'avatar': 'static/img/dota2heroes/silencer.png'},
	76: {'name': 'Outworld Destroyer', 'avatar': 'static/img/dota2heroes/outworld_destroyer.png'},
	77: {'name': 'Lycanthrope', 'avatar': 'static/img/dota2heroes/lycanthrope.png'},
	78: {'name': 'Brewmaster', 'avatar': 'static/img/dota2heroes/brewmaster.png'},
	79: {'name': 'Shadow Demon', 'avatar': 'static/img/dota2heroes/shadow_demon.png'},
	80: {'name': 'Lone Druid', 'avatar': 'static/img/dota2heroes/lone_druid.png'},
	81: {'name': 'Chaos Knight', 'avatar': 'static/img/dota2heroes/chaos_knight.png'},
	82: {'name': 'Meepo', 'avatar': 'static/img/dota2heroes/meepo.png'},
	83: {'name': 'Treant Protector', 'avatar': 'static/img/dota2heroes/treant_protector.png'},
	84: {'name': 'Ogre Magi', 'avatar': 'static/img/dota2heroes/ogre_magi.png'},
	85: {'name': 'Undying', 'avatar': 'static/img/dota2heroes/undying.png'},
	86: {'name': 'Rubick', 'avatar': 'static/img/dota2heroes/rubick.png'},
	87: {'name': 'Disruptor', 'avatar': 'static/img/dota2heroes/disruptor.png'},
	88: {'name': 'Nyx Assassin', 'avatar': 'static/img/dota2heroes/nyx_assassin.png'},
	89: {'name': 'Naga Siren', 'avatar': 'static/img/dota2heroes/naga_siren.png'},
	90: {'name': 'Keeper of the Light', 'avatar': 'static/img/dota2heroes/keeper_of_the_light.png'},
	91: {'name': 'Wisp', 'avatar': 'static/img/dota2heroes/wisp.png'},
	92: {'name': 'Visage', 'avatar': 'static/img/dota2heroes/visage.png'},
	93: {'name': 'Slark', 'avatar': 'static/img/dota2heroes/slark.png'},
	94: {'name': 'Medusa', 'avatar': 'static/img/dota2heroes/medusa.png'},
	95: {'name': 'Troll Warlord', 'avatar': 'static/img/dota2heroes/troll_warlord.png'},
	96: {'name': 'Centaur Warrunner', 'avatar': 'static/img/dota2heroes/centaur_warrunner.png'},
	97: {'name': 'Magnus', 'avatar': 'static/img/dota2heroes/magnus.png'},
	98: {'name': 'Timbersaw', 'avatar': 'static/img/dota2heroes/timbersaw.png'},
	100: {'name': 'Tusk', 'avatar': 'static/img/dota2heroes/tusk.png'}
		
}

Items = {

	0: {'avatar': 'data-src=holder.js/60x45/text:Empty'},
	1: {'name': 'Blink Dagger', 'avatar': 'static/img/dota2items/blink_dagger.png'},
	2: {'name': 'Blades of Attack', 'avatar': 'static/img/dota2items/blades_of_attack.png'},	
 	4: {'name': 'Chainmail', 'avatar': 'static/img/dota2items/chainmail.png'},
 	6: {'name': 'Helm of Iron Will', 'avatar': 'static/img/dota2items/helm_of_iron_will.png'},
 	7: {'name': 'Javelin', 'avatar': 'static/img/dota2items/javelin.png'},
 	8: {'name': 'Mithril Hammer', 'avatar': 'static/img/dota2items/mithril_hammer.png'}, 
 	9: {'name': 'Platemail', 'avatar': 'static/img/dota2items/platemail.png'},
 	11: {'name': 'Quelling Blade', 'avatar': 'static/img/dota2items/quelling_blade.png'},
 	12: {'name': 'Ring of Protection', 'avatar': 'static/img/dota2items/ring_of_protection.png'},
 	13: {'name': 'Gauntlets of Strength', 'avatar': 'static/img/dota2items/gauntlets_of_strength.png'},
	16: {'name': 'Iron Branch', 'avatar': 'static/img/dota2items/iron_branch.png'},
	17: {'name': 'Belt of Strength', 'avatar': 'static/img/dota2items/belt_of_strength.png'},
	19: {'name': 'Robe of the Magi', 'avatar': 'static/img/dota2items/robe_of_the_magi.png'},
 	21: {'name': 'Ogre Club', 'avatar': 'static/img/dota2items/ogre_club.png'},
 	23: {'name': 'Staff of Wizardry', 'avatar': 'static/img/dota2items/staff_of_wizardry.png'},
	24: {'name': 'Ultimate Orb', 'avatar': 'static/img/dota2items/ultimate_orb.png'},
	27: {'name': 'Ring of Regen', 'avatar': 'static/img/dota2items/ring_of_regen.png'},
	29: {'name': 'Boots of Speed', 'avatar': 'static/img/dota2items/boots_of_speed.png'},
	50: {'name': 'Phase Boots', 'avatar': 'static/img/dota2items/phase_boots.png'},
	63: {'name': 'Power Treads', 'avatar': 'static/img/dota2items/power_treads.png'},
	65: {'name': 'Hand of Midas', 'avatar': 'static/img/dota2items/hand_of_midas.png'},
	139: {'name': 'Butterfly', 'avatar': 'static/img/dota2items/butterfly.png'},
	152: {'name': 'Shadow Blade', 'avatar': 'static/img/dota2items/shadow_blade.png'},
	158: {'name': 'Mjollnir', 'avatar': 'static/img/dota2items/mjollnir.png'},
	168: {'name': 'Desolator', 'avatar': 'static/img/dota2items/desolator.png'},
	172: {'name': 'Mask of Madness', 'avatar': 'static/img/dota2items/mask_of_madness.png'},
	141: {'name': 'Daedalus', 'avatar': 'static/img/dota2items/daedalus.png'},
	180: {'name': 'Arcane Boots', 'avatar': 'static/img/dota2items/arcane_boots.png'},
	145: {'name': 'Battlefury', 'avatar': 'static/img/dota2items/battle_fury.png'},
	116: {'name': 'Black King Bar', 'avatar': 'static/img/dota2items/black_king_bar.png'},
	121: {'name': 'Bloodstone', 'avatar': 'static/img/dota2items/bloodstone.png'},
	48: {'name': 'Travel Boots', 'avatar': 'static/img/dota2items/boots_of_travel.png'},
	174: {'name': 'Diffusal Blade', 'avatar': 'static/img/dota2items/diffusal_blade.png'},
	147: {'name': 'Manta', 'avatar': 'static/img/dota2items/manta_style.png'},
	44: {'name': 'Tango', 'avatar': 'static/img/dota2items/tango.png'},
	143: {'name': 'Basher', 'avatar': 'static/img/dota2items/skull_basher.png'},
	214: {'name': 'Tranquil Boots', 'avatar': 'static/img/dota2items/tranquil_boots.png'},
	73: {'name': 'Bracer', 'avatar': 'static/img/dota2items/bracer.png'},
	75: {'name': 'Wraith Band', 'avatar': 'static/img/dota2items/wraith_band.png'},
	135: {'name': 'Monkey King Bar', 'avatar': 'static/img/dota2items/monkey_king_bar.png'},
	164: {'name': 'Helm of the Dominator', 'avatar': 'static/img/dota2items/helm_of_the_dominator.png'},
	79: {'name': 'Mekansm', 'avatar': 'static/img/dota2items/mekansm.png'},
	36: {'name': 'Magic Wand', 'avatar': 'static/img/dota2items/magic_wand.png'},
	46: {'name': 'Teleport Scroll', 'avatar': 'static/img/dota2items/town_portal_scroll.png'},
	71: {'name': 'Poor Man\'s Shield', 'avatar': 'static/img/dota2items/poor_mans_shield.png'},
	52: {'name': 'Eaglesong', 'avatar': 'static/img/dota2items/eaglesong.png'},
	125: {'name': 'Vanguard', 'avatar': 'static/img/dota2items/vanguard.png'},
	127: {'name': 'Blade Mail', 'avatar': 'static/img/dota2items/blade_mail.png'},
	108: {'name': 'Aghanim\'s Scepter', 'avatar': 'static/img/dota2items/aghanims_scepter.png'},
	102: {'name': 'Force Staff', 'avatar': 'static/img/dota2items/force_staff.png'},
	92: {'name': 'Urn of Shadows', 'avatar': 'static/img/dota2items/urn_of_shadows.png'},
	212: {'name': 'Ring of Aquila', 'avatar': 'static/img/dota2items/ring_of_aquila.png'},
	185: {'name': 'Drum of Endurance', 'avatar': 'static/img/dota2items/drum_of_endurance.png'},
	123: {'name': 'Linken\'s Sphere', 'avatar': 'static/img/dota2items/linkens_sphere.png'},
	39: {'name': 'Healing Salve', 'avatar': 'static/img/dota2items/healing_salve.png'},
	182: {'name': 'Stout Shield', 'avatar': 'static/img/dota2items/stout_shield.png'},
	114: {'name': 'Heart of Tarrasque', 'avatar': 'static/img/dota2items/heart_of_tarrasque.png'},
	151: {'name': 'Armlet of Mordiggian', 'avatar': 'static/img/dota2items/armlet_of_mordiggian.png'},
	98: {'name': 'Orchid Malevolence', 'avatar': 'static/img/dota2items/orchid_malevolence.png'},
	110: {'name': 'Refresher Orb', 'avatar': 'static/img/dota2items/refresher_orb.png'},
 	170: {'name': 'Yasha', 'avatar': 'static/img/dota2items/yasha.png'},
 	41: {'name': 'Bottle', 'avatar': 'static/img/dota2items/bottle.png'},
 	160: {'name': 'Eye of Skadi', 'avatar': 'static/img/dota2items/eye_of_skadi.png'},
 	178: {'name': 'Soul Ring', 'avatar': 'static/img/dota2items/soul_ring.png'},
 	215: {'name': 'Shadow Amulet', 'avatar': 'static/img/dota2items/shadow_amulet.png'},
 	149: {'name': 'Crystalys', 'avatar': 'static/img/dota2items/crystalys.png'},
 	88: {'name': 'Ring of Basilius', 'avatar': 'static/img/dota2items/ring_of_basilius.png'},
 	42: {'name': 'Observer Ward', 'avatar': 'static/img/dota2items/observer_ward.png'},
 	81: {'name': 'Vladmir\'s Offering', 'avatar': 'static/img/dota2items/vladmirs_offering.png'},
 	90: {'name': 'Pipe of Insight', 'avatar': 'static/img/dota2items/pipe_of_insight.png'},
 	112: {'name': 'Assault Cuirass', 'avatar': 'static/img/dota2items/assault_cuirass.png'},
 	100: {'name': 'Euls Scepter of Divinity', 'avatar': 'static/img/dota2items/euls_scepter_of_divinity.png'},
 	119: {'name': 'Shiva\'s Guard', 'avatar': 'static/img/dota2items/shivas_guard.png'},
 	208: {'name': 'Abyssal Blade', 'avatar': 'static/img/dota2items/abyssal_blade.png'},
 	210: {'name': 'Heaven\'s Halberd', 'avatar': 'static/img/dota2items/heavens_halberd.png'},
 	37: {'name': 'Ghost Scepter', 'avatar': 'static/img/dota2items/ghost_scepter.png'},
 	51: {'name': 'Demon Edge', 'avatar': 'static/img/dota2items/demon_edge.png'},
 	96: {'name': 'Scythe of Vyse', 'avatar': 'static/img/dota2items/scythe_of_vyse.png'},
 	53: {'name': 'Reaver', 'avatar': 'static/img/dota2items/reaver.png'},
 	77: {'name': 'Null Talisman', 'avatar': 'static/img/dota2items/null_talisman.png'},
 	137: {'name': 'Radiance', 'avatar': 'static/img/dota2items/radiance.png'},
 	204: {'name': 'Dagon Level 5', 'avatar': 'static/img/dota2items/dagon.png'},
 	57: {'name': 'Void Stone', 'avatar': 'static/img/dota2items/void_stone.png'},	
 	131: {'name': 'Hood of Defiance', 'avatar': 'static/img/dota2items/hood_of_defiance.png'},
 	202: {'name': 'Dagon Level 3', 'avatar': 'static/img/dota2items/dagon_3.png'},
 	94: {'name': 'Headdress', 'avatar': 'static/img/dota2items/headdress.png'},
 	34: {'name': 'Magic Stick', 'avatar': 'static/img/dota2items/magic_stick.png'},
	38: {'name': 'Clarity', 'avatar': 'static/img/dota2items/clarity.png'},
 	40: {'name': 'Dust of Appearance', 'avatar': 'static/img/dota2items/dust_of_appearance.png'},
 	60: {'name': 'Point Booster', 'avatar': 'static/img/dota2items/point_booster.png'},
 	166: {'name': 'Maelstrom', 'avatar': 'static/img/dota2items/maelstrom.png'},
 	154: {'name': 'Sange and Yasha', 'avatar': 'static/img/dota2items/sange_and_yasha.png'},
 	69: {'name': 'Perseverance', 'avatar': 'static/img/dota2items/perseverance.png'},
 	55: {'name': 'Hyperstone', 'avatar': 'static/img/dota2items/hyperstone.png'},
 	28: {'name': 'Sage\'s Mask', 'avatar': 'static/img/dota2items/sages_mask.png'},
 	206: {'name': 'Rod of Atos', 'avatar': 'static/img/dota2items/rod_of_atos.png'},
 	5: {'name': 'Claymore', 'avatar': 'static/img/dota2items/claymore.png'},
 	59: {'name': 'Energy Booster', 'avatar': 'static/img/dota2items/energy_booster.png'},
 	30: {'name': 'Gem of True Sight', 'avatar': 'static/img/dota2items/gem_of_true_sight.png'},
 	26: {'name': 'Morbid Mask', 'avatar': 'static/img/dota2items/morbid_mask.png'}

}