# -*- coding: utf-8 -*-
# Welcome
# Dota 2 Heroes Library
# All Right Reserved
# Last update: March 10, 2013

Heroes = {
	
	1: {'name': 'Antimage', 'avatar': 'static/img/dota2heroes/anti_mage.png'},
	2: {'name': 'Axe', 'avatar': 'static/img/dota2heroes/axe.png'},
	3: {'name': 'Ban', 'avatar': 'static/img/dota2heroes/ban.png'},
	4: {'name': 'Bloodseeker', 'avatar': 'static/img/dota2heroes/bloodseeker.png'},
	5: {'name': 'Crystal Maiden', 'avatar': 'static/img/dota2heroes/crystal_maiden.png'},
	6: {'name': 'Drow Ranger', 'avatar': 'static/img/dota2heroes/drow_ranger.png'},
	7: {'name': 'Earthshaker', 'avatar': 'static/img/dota2heroes/earthshaker.png'},
	8: {'name': 'Juggernaut', 'avatar': 'static/img/dota2heroes/juggernaut.png'},
	9: {'name': 'Mirana', 'avatar': 'static/img/dota2heroes/mirana.png'},
	10: {'name': 'Morphling', 'avatar': 'static/img/dota2heroes/morphling.png'},
	11: {'name': 'Shadow Fiend', 'avatar': 'static/img/dota2heroes/shadow_fiend.png'},
	12: {'name': 'Phantom Lancer', 'avatar': 'static/img/dota2heroes/phantom_lancer.png'},
	13: {'name': 'Puck', 'avatar': 'static/img/dota2heroes/puck.png'},
	14: {'name': 'Pudge', 'avatar': 'static/img/dota2heroes/pudge.png'},
	15: {'name': 'Razor', 'avatar': 'static/img/dota2heroes/razor.png'},
	16: {'name': 'Sand King', 'avatar': 'static/img/dota2heroes/sand_king.png'},
	17: {'name': 'Storm Spirit', 'avatar': 'static/img/dota2heroes/storm_spirit.png'},
	18: {'name': 'Sven', 'avatar': 'static/img/dota2heroes/sven.png'},
	19: {'name': 'Tiny', 'avatar': 'static/img/dota2heroes/tiny.png'},
	20: {'name': 'Vengeful Spirit', 'avatar': 'static/img/dota2heroes/vengeful_spirit.png'},
	21: {'name': 'Windrunner', 'avatar': 'static/img/dota2heroes/windrunner.png'},
	22: {'name': 'Zeus', 'avatar': 'static/img/dota2heroes/zeus.png'},
	23: {'name': 'Kunkka', 'avatar': 'static/img/dota2heroes/kunkka.png'},
	25: {'name': 'Lina', 'avatar': 'static/img/dota2heroes/lina.png'},
	26: {'name': 'Lion', 'avatar': 'static/img/dota2heroes/lion.png'},
	27: {'name': 'Shadow Shaman', 'avatar': 'static/img/dota2heroes/shadow_shaman.png'},
	28: {'name': 'Slardar', 'avatar': 'static/img/dota2heroes/slardar.png'},
	29: {'name': 'Tidehunter', 'avatar': 'static/img/dota2heroes/tidehunter.png'},
	30: {'name': 'Witch Doctor', 'avatar': 'static/img/dota2heroes/witch_doctor.png'},
	31: {'name': 'Lich', 'avatar': 'static/img/dota2heroes/lich.png'},
	32: {'name': 'Riki', 'avatar': 'static/img/dota2heroes/riki.png'},
	33: {'name': 'Enigma', 'avatar': 'static/img/dota2heroes/enigma.png'},
	34: {'name': 'Tinker', 'avatar': 'static/img/dota2heroes/tinker.png'},
	35: {'name': 'Sniper', 'avatar': 'static/img/dota2heroes/sniper.png'},
	36: {'name': 'Necrolyte', 'avatar': 'static/img/dota2heroes/necrolyte.png'},
	37: {'name': 'Warlock', 'avatar': 'static/img/dota2heroes/warlock.png'},
	38: {'name': 'Beastmaster', 'avatar': 'static/img/dota2heroes/beastmaster.png'},
	39: {'name': 'Queen of Pain', 'avatar': 'static/img/dota2heroes/queen_of_pain.png'},
	40: {'name': 'Venomancer', 'avatar': 'static/img/dota2heroes/venomancer.png'},
	41: {'name': 'Faceless Void', 'avatar': 'static/img/dota2heroes/faceless_void.png'},
	42: {'name': 'Skeleton King', 'avatar': 'static/img/dota2heroes/skeleton_king.png'},
	43: {'name': 'Death Prophet', 'avatar': 'static/img/dota2heroes/death_prophet.png'},
	44: {'name': 'Phantom Assassin', 'avatar': 'static/img/dota2heroes/phantom_assassin.png'},
	45: {'name': 'Pugna', 'avatar': 'static/img/dota2heroes/pugna.png'},
	46: {'name': 'Templar Assassin', 'avatar': 'static/img/dota2heroes/templar_assassin.png'},
	47: {'name': 'Viper', 'avatar': 'static/img/dota2heroes/viper.png'},
	48: {'name': 'Luna', 'avatar': 'static/img/dota2heroes/luna.png'},
	49: {'name': 'Dragon Knight', 'avatar': 'static/img/dota2heroes/dragon_knight.png'},
	50: {'name': 'Dazzle', 'avatar': 'static/img/dota2heroes/dazzle.png'},
	51: {'name': 'Clockwerk', 'avatar': 'static/img/dota2heroes/clockwerk.png'},
	52: {'name': 'Leshrac', 'avatar': 'static/img/dota2heroes/leshrac.png'},
	53: {'name': 'Natures Prophet', 'avatar': 'static/img/dota2heroes/natures_prophet.png'},
	54: {'name': 'Lifestealer', 'avatar': 'static/img/dota2heroes/lifestealer.png'},
	55: {'name': 'Dark Seer', 'avatar': 'static/img/dota2heroes/dark_seer.png'},
	56: {'name': 'Clinkz', 'avatar': 'static/img/dota2heroes/clinkz.png'},
	57: {'name': 'Omniknight', 'avatar': 'static/img/dota2heroes/omniknight.png'},
	58: {'name': 'Enchantress', 'avatar': 'static/img/dota2heroes/enchantress.png'},
	59: {'name': 'Huskar', 'avatar': 'static/img/dota2heroes/huskar.png'},
	60: {'name': 'Night Stalker', 'avatar': 'static/img/dota2heroes/night_stalker.png'},
	61: {'name': 'Broodmother', 'avatar': 'static/img/dota2heroes/broodmother.png'},
	62: {'name': 'Bounty Hunter', 'avatar': 'static/img/dota2heroes/bounty_hunter.png'},
	63: {'name': 'Weaver', 'avatar': 'static/img/dota2heroes/weaver.png'},
	64: {'name': 'Jakiro', 'avatar': 'static/img/dota2heroes/jakiro.png'},
	65: {'name': 'Batrider', 'avatar': 'static/img/dota2heroes/batrider.png'},
	66: {'name': 'Chen', 'avatar': 'static/img/dota2heroes/chen.png'},
	67: {'name': 'Spectre', 'avatar': 'static/img/dota2heroes/spectre.png'},
	68: {'name': 'Ancient Apparition', 'avatar': 'static/img/dota2heroes/ancient_aparition.png'},
	69: {'name': 'Doom Bringer', 'avatar': 'static/img/dota2heroes/doom_bringer.png'},
	70: {'name': 'Ursa', 'avatar': 'static/img/dota2heroes/ursa.png'},
	71: {'name': 'Spirit Breaker', 'avatar': 'static/img/dota2heroes/spirit_breaker.png'},
	72: {'name': 'Gyrocopter', 'avatar': 'static/img/dota2heroes/gyrocopter.png'},
	73: {'name': 'Alchemist', 'avatar': 'static/img/dota2heroes/alchemist.png'},
	74: {'name': 'Invoker', 'avatar': 'static/img/dota2heroes/invoker.png'},
	75: {'name': 'Silencer', 'avatar': 'static/img/dota2heroes/silencer.png'},
	76: {'name': 'Outworld Destroyer', 'avatar': 'static/img/dota2heroes/outworld_destroyer.png'},
	77: {'name': 'Lycanthrope', 'avatar': 'static/img/dota2heroes/lycanthrope.png'},
	78: {'name': 'Brewmaster', 'avatar': 'static/img/dota2heroes/brewmaster.png'},
	79: {'name': 'Shadow Demon', 'avatar': 'static/img/dota2heroes/shadow_demon.png'},
	80: {'name': 'Lone Druid', 'avatar': 'static/img/dota2heroes/lone_druid.png'},
	81: {'name': 'Chaos Knight', 'avatar': 'static/img/dota2heroes/chaos_knight.png'},
	82: {'name': 'Meepo', 'avatar': 'static/img/dota2heroes/meepo.png'},
	83: {'name': 'Treant Protector', 'avatar': 'static/img/dota2heroes/treant_protector.png'},
	84: {'name': 'Ogre Magi', 'avatar': 'static/img/dota2heroes/ogre_magi.png'},
	85: {'name': 'Undying', 'avatar': 'static/img/dota2heroes/undying.png'},
	86: {'name': 'Rubick', 'avatar': 'static/img/dota2heroes/rubick.png'},
	87: {'name': 'Disruptor', 'avatar': 'static/img/dota2heroes/disruptor.png'},
	88: {'name': 'Nyx Assassin', 'avatar': 'static/img/dota2heroes/nyx_assassin.png'},
	89: {'name': 'Naga Siren', 'avatar': 'static/img/dota2heroes/naga_siren.png'},
	90: {'name': 'Keeper of the Light', 'avatar': 'static/img/dota2heroes/keeper_of_the_light.png'},
	91: {'name': 'Wisp', 'avatar': 'static/img/dota2heroes/wisp.png'},
	92: {'name': 'Visage', 'avatar': 'static/img/dota2heroes/visage.png'},
	93: {'name': 'Slark', 'avatar': 'static/img/dota2heroes/slark.png'},
	94: {'name': 'Medusa', 'avatar': 'static/img/dota2heroes/medusa.png'},
	95: {'name': 'Troll Warlord', 'avatar': 'static/img/dota2heroes/troll_warlord.png'},
	96: {'name': 'Centaur Warrunner', 'avatar': 'static/img/dota2heroes/centaur_warrunner.png'},
	97: {'name': 'Magnus', 'avatar': 'static/img/dota2heroes/magnus.png'},
	98: {'name': 'Timbersaw', 'avatar': 'static/img/dota2heroes/timbersaw.png'},
	100: {'name': 'Tusk', 'avatar': 'static/img/dota2heroes/tusk.png'},
		
}